import type { ExamConfig } from "@/lib/types";

export const examConfig: ExamConfig = {
  id: "harec",
  name: "HAREC",
  fullName: "Harmonised Amateur Radio Examination Certificate — třída A",
  locale: "cs-CZ",
  parts: [
    {
      id: "regulations",
      name: "Radiokomunikační předpisy",
      icon: "Scale",
      examQuestionCount: 20,
      sections: [
        {
          id: "itu",
          name: "Předpisy ITU",
          topicSlug: "predpisy-itu",
          examQuestionCount: 6,
          bankQuestionCount: 16,
        },
        {
          id: "cept",
          name: "Předpisy CEPT",
          topicSlug: "predpisy-cept",
          examQuestionCount: 2,
          bankQuestionCount: 16,
        },
        {
          id: "czech-law",
          name: "Předpisy vycházející z legislativy ČR",
          topicSlug: "predpisy-cr",
          examQuestionCount: 12,
          bankQuestionCount: 48,
        },
      ],
    },
    {
      id: "operating",
      name: "Radiokomunikační provoz",
      icon: "Radio",
      examQuestionCount: 40,
      sections: [
        {
          id: "frequencies",
          name: "Rozvrh kmitočtů a druhů provozu",
          topicSlug: "kmitocty-a-druhy-provozu",
          examQuestionCount: 6,
          bankQuestionCount: 41,
        },
        {
          id: "phonetic",
          name: "Hláskovací abeceda (česká a mezinárodní)",
          topicSlug: "hlaskovaci-abeceda",
          examQuestionCount: 3,
          bankQuestionCount: 52,
        },
        {
          id: "skills",
          name: "Provozní dovednosti",
          topicSlug: "provozni-dovednosti",
          examQuestionCount: 4,
          bankQuestionCount: 30,
        },
        {
          id: "q-codes",
          name: "Q kódy",
          topicSlug: "q-kody",
          examQuestionCount: 4,
          bankQuestionCount: 21,
        },
        {
          id: "abbreviations",
          name: "Zkratky používané v radioamatérské komunikaci",
          topicSlug: "zkratky",
          examQuestionCount: 15,
          bankQuestionCount: 140,
        },
        {
          id: "prefixes",
          name: "Používání prefixů ve volacích značkách",
          topicSlug: "prefixy",
          examQuestionCount: 8,
          bankQuestionCount: 85,
        },
      ],
    },
    {
      id: "technical",
      name: "Elektrotechnika a radiotechnika",
      icon: "Zap",
      examQuestionCount: 20,
      sections: [
        {
          id: "theory",
          name: "Elektrická, elektromagnetická a rádiová teorie",
          topicSlug: "elektricka-teorie",
          examQuestionCount: 4,
          bankQuestionCount: 22,
        },
        {
          id: "components",
          name: "Součástky",
          topicSlug: "soucastky",
          examQuestionCount: 2,
          bankQuestionCount: 11,
        },
        {
          id: "circuits",
          name: "Elektrické obvody",
          topicSlug: "elektricke-obvody",
          examQuestionCount: 4,
          bankQuestionCount: 15,
        },
        {
          id: "receivers",
          name: "Rádiové přijímače",
          topicSlug: "radiove-prijimace",
          examQuestionCount: 2,
          bankQuestionCount: 15,
        },
        {
          id: "transmitters",
          name: "Rádiové vysílače",
          topicSlug: "radiove-vysilace",
          examQuestionCount: 2,
          bankQuestionCount: 11,
        },
        {
          id: "antennas",
          name: "Antény a napájecí vedení",
          topicSlug: "anteny-a-napajeci-vedeni",
          examQuestionCount: 1,
          bankQuestionCount: 15,
        },
        {
          id: "propagation",
          name: "Šíření rádiových vln",
          topicSlug: "sireni-radiovych-vln",
          examQuestionCount: 1,
          bankQuestionCount: 17,
        },
        {
          id: "measurements",
          name: "Měření elektrických veličin",
          topicSlug: "mereni-elektrickych-velicin",
          examQuestionCount: 1,
          bankQuestionCount: 8,
        },
        {
          id: "interference",
          name: "Rušení a odolnost proti rušení",
          topicSlug: "ruseni-a-odolnost",
          examQuestionCount: 2,
          bankQuestionCount: 9,
        },
        {
          id: "safety",
          name: "Bezpečnost elektrických zařízení",
          topicSlug: "bezpecnost",
          examQuestionCount: 1,
          bankQuestionCount: 12,
        },
      ],
    },
  ],
  examRules: {
    totalQuestions: 80,
    timeLimitMinutes: 120,
    passPercentage: 60,
    shuffleQuestions: true,
    shuffleChoices: true,
  },
  theme: {
    accentColor: "oklch(0.50 0.18 250)",
    accentForeground: "oklch(0.98 0.002 75)",
  },
};
