import type { Question } from "@/lib/types";

export const operatingPrefixesQuestions: Question[] = [
  // -----------------------------------------------------------------------
  // Callsign structure, OK/OL, portable/mobile (prefixes-01)
  // O-PRF-001 to O-PRF-028
  // -----------------------------------------------------------------------
  {
    id: "O-PRF-001",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Z jakych casti se sklada radioamaterskam volaci znacka?",
    choices: [
      { id: "a", text: "Prefix, cislice, suffix" },
      { id: "b", text: "Prefix, suffix, lomitko" },
      { id: "c", text: "Zeme, mesto, jmeno" },
      { id: "d", text: "Region, frekvence, cislo" },
    ],
    correctChoiceId: "a",
    explanation:
      "Volaci znacka ma tri casti: prefix (zeme), cislice (oblast/kategorie) a suffix (unikatni oznaceni). Lomitko neni soucast zakladni struktury.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-002",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co oznacuje prefix ve volaci znacce?",
    choices: [
      { id: "a", text: "Zemi, ve ktere je stanice registrovana" },
      { id: "b", text: "Oblast v ramci zeme" },
      { id: "c", text: "Typ vysildace" },
      { id: "d", text: "Frekvencni pasmo" },
    ],
    correctChoiceId: "a",
    explanation:
      "Prefix urcuje zemi registrace stanice. Oblast se oznacuje cislici za prefixem. Typ vysilace ani pasmo se z volaci znacky neurci.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-003",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jake prefixy pouziva Ceska republika?",
    choices: [
      { id: "a", text: "OK a OL" },
      { id: "b", text: "OK a OM" },
      { id: "c", text: "CZ a OK" },
      { id: "d", text: "OL a OM" },
    ],
    correctChoiceId: "a",
    explanation:
      "Ceska republika ma prefixy OK (tradicni) a OL (dodatecny blok). OM je Slovensko, CZ neni radioamatersky prefix.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-004",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jaky je prefix ve volaci znacce OK1ABC?",
    choices: [
      { id: "a", text: "OK" },
      { id: "b", text: "OK1" },
      { id: "c", text: "O" },
      { id: "d", text: "OK1A" },
    ],
    correctChoiceId: "a",
    explanation:
      "Prefix je cast pred cislici - tedy OK. Cislice 1 neni soucasti prefixu, oddeluje prefix od suffixu.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-005",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co oznacuje cislice ve volaci znacce OK2XYZ?",
    choices: [
      { id: "a", text: "Oblast nebo kategorii v ramci zeme" },
      { id: "b", text: "Pocet operatoru na stanici" },
      { id: "c", text: "Rok ziskani licence" },
      { id: "d", text: "Vykonovou tridu" },
    ],
    correctChoiceId: "a",
    explanation:
      "Cislice za prefixem oznacuje oblast ci kategorii (napriklad okres). Nema nic spolecneho s poctem operatoru ani rokem licence.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-006",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co znamena oznaceni /P za volaci znackou?",
    choices: [
      { id: "a", text: "Prenosna stanice (portable)" },
      { id: "b", text: "Mobilni stanice" },
      { id: "c", text: "Namorni mobilni stanice" },
      { id: "d", text: "Stanice v zahranici" },
    ],
    correctChoiceId: "a",
    explanation:
      "/P = portable (prenosna). /M = mobile (mobilni), /MM = maritime mobile (namorni). Provoz ze zahranici se oznacuje prefixem hostitelske zeme.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-007",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co znamena oznaceni /M za volaci znackou?",
    choices: [
      { id: "a", text: "Mobilni stanice" },
      { id: "b", text: "Prenosna stanice" },
      { id: "c", text: "Namorni mobilni stanice" },
      { id: "d", text: "Letecka mobilni stanice" },
    ],
    correctChoiceId: "a",
    explanation:
      "/M = mobile (mobilni, napriklad z automobilu). /P = portable, /MM = maritime mobile, /AM = aeronautical mobile.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-008",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co znamena oznaceni /MM za volaci znackou?",
    choices: [
      { id: "a", text: "Namorni mobilni stanice (maritime mobile)" },
      { id: "b", text: "Dvojita mobilni stanice" },
      { id: "c", text: "Mobilni stanice s velkym vykonem" },
      { id: "d", text: "Prenosna stanice na hore" },
    ],
    correctChoiceId: "a",
    explanation:
      "/MM = maritime mobile, provoz z lode na mori. Nejedna se o zdvojeny suffix /M.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-009",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Odkud vysila stanice OE/OK1ABC?",
    choices: [
      { id: "a", text: "Z Rakouska" },
      { id: "b", text: "Z Ceske republiky" },
      { id: "c", text: "Z Nemecka" },
      { id: "d", text: "Ze Slovenska" },
    ],
    correctChoiceId: "a",
    explanation:
      "OE pred lomitkem oznacuje zemi, ze ktere stanice vysila - OE = Rakousko. OK1ABC je domaci znacka ceskeho operatora.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-010",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Odkud vysila stanice SP/OK2DEF?",
    choices: [
      { id: "a", text: "Z Polska" },
      { id: "b", text: "Z Ceske republiky" },
      { id: "c", text: "Ze Slovenska" },
      { id: "d", text: "Ze Spanelska" },
    ],
    correctChoiceId: "a",
    explanation:
      "SP pred lomitkem = stanice vysila z Polska. OK2DEF je domaci ceska znacka operatora.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-011",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jak se oznaci cesky radioamater OK1ABC vysilajici z Nemecka?",
    choices: [
      { id: "a", text: "DL/OK1ABC" },
      { id: "b", text: "OK1ABC/DL" },
      { id: "c", text: "DL-OK1ABC" },
      { id: "d", text: "OK1ABC/D" },
    ],
    correctChoiceId: "a",
    explanation:
      "Prefix hostitelske zeme se pise pred lomitko a domaci znacku: DL/OK1ABC. Poradi je dulezite - prefix hostitelske zeme je vzdy prvni.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-012",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co je suffix ve volaci znacce OK1ABC?",
    choices: [
      { id: "a", text: "ABC" },
      { id: "b", text: "OK" },
      { id: "c", text: "1ABC" },
      { id: "d", text: "OK1" },
    ],
    correctChoiceId: "a",
    explanation:
      "Suffix je cast za cislici - ABC. Unikatne identifikuje konkretniho operatora v ramci dane zeme a oblasti.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-013",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera volaci znacka patri ceske stanici?",
    choices: [
      { id: "a", text: "OL5ABC" },
      { id: "b", text: "OM3ABC" },
      { id: "c", text: "OE1ABC" },
      { id: "d", text: "DL2ABC" },
    ],
    correctChoiceId: "a",
    explanation:
      "OL je cesky prefix. OM = Slovensko, OE = Rakousko, DL = Nemecko.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-014",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Kolik pismen muze mit suffix volaci znacky?",
    choices: [
      { id: "a", text: "Jedno az tri" },
      { id: "b", text: "Vzdy presne tri" },
      { id: "c", text: "Vzdy presne dve" },
      { id: "d", text: "Ctyri az pet" },
    ],
    correctChoiceId: "a",
    explanation:
      "Suffix ma jedno az tri pismena. Napriklad OK1A (jedno), OK1AB (dve) nebo OK1ABC (tri) jsou vsechny platne znacky.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-015",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co oznacuje prefix OL?",
    choices: [
      { id: "a", text: "Ceska republika" },
      { id: "b", text: "Slovensko" },
      { id: "c", text: "Nizozemsko" },
      { id: "d", text: "Norsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "OL je druhy cesky prefix vedle OK. Slovensko = OM, Nizozemsko = PA, Norsko = LA.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-016",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jaka je domaci zeme stanice s volaci znackou OM3BCS?",
    choices: [
      { id: "a", text: "Slovensko" },
      { id: "b", text: "Ceska republika" },
      { id: "c", text: "Oman" },
      { id: "d", text: "Moldavsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "OM = Slovensko. OK/OL = Ceska republika, A4 = Oman, ER = Moldavsko.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-017",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co znamena volaci znacka OK1ABC/AM?",
    choices: [
      { id: "a", text: "Letecka mobilni stanice (aeronautical mobile)" },
      { id: "b", text: "Stanice v Americe" },
      { id: "c", text: "Amaterska stanice" },
      { id: "d", text: "Automaticky mod" },
    ],
    correctChoiceId: "a",
    explanation:
      "/AM = aeronautical mobile, provoz z letadla. Nesouvisim s Amerikou ani s automatickym modem.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-018",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Stanice vysila pod znackou HA/OK1ABC. Kde se fyzicky nachazi?",
    choices: [
      { id: "a", text: "V Madarsku" },
      { id: "b", text: "V Ceske republice" },
      { id: "c", text: "V Rakousku" },
      { id: "d", text: "Na Slovensku" },
    ],
    correctChoiceId: "a",
    explanation:
      "HA pred lomitkem = stanice je v Madarsku. OK1ABC je domaci znacka ceskeho operatora.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-019",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Ktera cast volaci znacky jednoznacne identifikuje konkretniho operatora?",
    choices: [
      { id: "a", text: "Suffix" },
      { id: "b", text: "Prefix" },
      { id: "c", text: "Cislice" },
      { id: "d", text: "Lomitko" },
    ],
    correctChoiceId: "a",
    explanation:
      "Suffix (pismena za cislici) je unikatni pro kazdeho operatora. Prefix urcuje zemi, cislice oblast.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-020",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jaky prefix ma Slovensko?",
    choices: [
      { id: "a", text: "OM" },
      { id: "b", text: "OK" },
      { id: "c", text: "OE" },
      { id: "d", text: "SL" },
    ],
    correctChoiceId: "a",
    explanation:
      "OM = Slovensko. OK = Ceska republika, OE = Rakousko. SL neni platny radioamatersky prefix.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-021",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jaky prefix ma Rakousko?",
    choices: [
      { id: "a", text: "OE" },
      { id: "b", text: "AU" },
      { id: "c", text: "AT" },
      { id: "d", text: "OM" },
    ],
    correctChoiceId: "a",
    explanation:
      "OE = Rakousko (Oesterreich). AU a AT nejsou radioamaterske prefixy. OM = Slovensko.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-022",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Kdo prideluje radioamaterske prefixy jednotlivym zemim?",
    choices: [
      { id: "a", text: "ITU (Mezinarodni telekomunikacni unie)" },
      { id: "b", text: "IARU (Mezinarodni radioamaterskam unie)" },
      { id: "c", text: "OSN (Organizace spojenych narodu)" },
      { id: "d", text: "NATO" },
    ],
    correctChoiceId: "a",
    explanation:
      "Prefixy prideluje ITU. IARU je mezinarodni organizace radioamateru, ale neprideluje prefixy. OSN a NATO nemaji s prefixy nic spolecneho.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-023",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Cesky radioamater OK1XY vysila z prenosne stanice v horach. Jakou znacku pouzije?",
    choices: [
      { id: "a", text: "OK1XY/P" },
      { id: "b", text: "OK1XY/M" },
      { id: "c", text: "OK1XY/MM" },
      { id: "d", text: "P/OK1XY" },
    ],
    correctChoiceId: "a",
    explanation:
      "/P se pridava za znacku pro prenosny provoz. /M je pro mobilni provoz (z vozidla). Oznaceni se vzdy pridava za vlastni znacku.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-024",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera volaci znacka oznacuje stanici z Ceske republiky?",
    choices: [
      { id: "a", text: "OK3AB" },
      { id: "b", text: "OE5AB" },
      { id: "c", text: "OM7AB" },
      { id: "d", text: "SP9AB" },
    ],
    correctChoiceId: "a",
    explanation:
      "OK = Ceska republika. OE = Rakousko, OM = Slovensko, SP = Polsko.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-025",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Jak se od sebe lisi prefixy OK a OL?",
    choices: [
      { id: "a", text: "Oba jsou ceske - OK je tradicni, OL je dodatecny blok" },
      { id: "b", text: "OK je Cesko, OL je Slovensko" },
      { id: "c", text: "OK je pro KV, OL pro VHF" },
      { id: "d", text: "OK je pro individualni, OL pro klubove stanice" },
    ],
    correctChoiceId: "a",
    explanation:
      "OK i OL jsou ceske prefixy. Rozdeleni na pasma nebo typ stanice neni spravne - oba se pouzivaji pro vsechny druhy provozu.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-026",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Stanice OK1ABC vysila z automobilu. Jaky suffix prida?",
    choices: [
      { id: "a", text: "/M" },
      { id: "b", text: "/P" },
      { id: "c", text: "/MM" },
      { id: "d", text: "/AM" },
    ],
    correctChoiceId: "a",
    explanation:
      "/M = mobile (z vozidla). /P = prenosna, /MM = namorni mobilni (z lode), /AM = letecka mobilni.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-027",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Kolik cislicmezi prefixem a suffixem obsahuje standardni volaci znacka?",
    choices: [
      { id: "a", text: "Jednu" },
      { id: "b", text: "Dve" },
      { id: "c", text: "Zadnou" },
      { id: "d", text: "Tri" },
    ],
    correctChoiceId: "a",
    explanation:
      "Standardni volaci znacka obsahuje prave jednu cislici mezi prefixem a suffixem, napriklad OK1ABC.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-028",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Prefix ve volaci znacce muze obsahovat:",
    choices: [
      { id: "a", text: "Jedno az tri pismena" },
      { id: "b", text: "Vzdy presne dve pismena" },
      { id: "c", text: "Pismena i cislice dohromady" },
      { id: "d", text: "Vzdy jedno pismeno" },
    ],
    correctChoiceId: "a",
    explanation:
      "Prefix ma jedno az tri pismena (napriklad I pro Italii, OK pro Cesko, HB9 vsak obsahuje cislici - to je vyjimka u nekterych prefixu). Bezne prefixy jsou jedno az dvoupismenne.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },

  // -----------------------------------------------------------------------
  // European prefixes (prefixes-02)
  // O-PRF-029 to O-PRF-057
  // -----------------------------------------------------------------------
  {
    id: "O-PRF-029",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix DL?",
    choices: [
      { id: "a", text: "Nemecko" },
      { id: "b", text: "Dansko" },
      { id: "c", text: "Nizozemsko" },
      { id: "d", text: "Lucembursko" },
    ],
    correctChoiceId: "a",
    explanation:
      "DL = Nemecko (Deutschland). Dansko = OZ, Nizozemsko = PA, Lucembursko = LX.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-030",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix SP?",
    choices: [
      { id: "a", text: "Polsko" },
      { id: "b", text: "Spanelsko" },
      { id: "c", text: "Portugalsko" },
      { id: "d", text: "Svedsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "SP = Polsko. Spanelsko = EA, Portugalsko = CT, Svedsko = SM.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-031",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix HA?",
    choices: [
      { id: "a", text: "Madarsko" },
      { id: "b", text: "Chorvatsko" },
      { id: "c", text: "Nizozemsko" },
      { id: "d", text: "Finsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "HA = Madarsko (Hungary/Magyarorszag). Chorvatsko = 9A, Nizozemsko = PA, Finsko = OH.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-032",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix OE?",
    choices: [
      { id: "a", text: "Rakousko" },
      { id: "b", text: "Ceska republika" },
      { id: "c", text: "Slovensko" },
      { id: "d", text: "Norsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "OE = Rakousko (Oesterreich). OK/OL = Cesko, OM = Slovensko, LA = Norsko.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-033",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix OM?",
    choices: [
      { id: "a", text: "Slovensko" },
      { id: "b", text: "Ceska republika" },
      { id: "c", text: "Oman" },
      { id: "d", text: "Moldavsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "OM = Slovensko. OK/OL = Ceska republika, A4 = Oman, ER = Moldavsko.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-034",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix I?",
    choices: [
      { id: "a", text: "Italie" },
      { id: "b", text: "Irsko" },
      { id: "c", text: "Island" },
      { id: "d", text: "Izrael" },
    ],
    correctChoiceId: "a",
    explanation:
      "I = Italie. Irsko = EI, Island = TF, Izrael = 4X.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-035",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix F?",
    choices: [
      { id: "a", text: "Francie" },
      { id: "b", text: "Finsko" },
      { id: "c", text: "Filipiny" },
      { id: "d", text: "Fidzi" },
    ],
    correctChoiceId: "a",
    explanation:
      "F = Francie. Finsko = OH, Filipiny = DU, Fidzi = 3D.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-036",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix G?",
    choices: [
      { id: "a", text: "Velka Britanie (Anglie)" },
      { id: "b", text: "Nemecko" },
      { id: "c", text: "Recko" },
      { id: "d", text: "Gruzie" },
    ],
    correctChoiceId: "a",
    explanation:
      "G = Velka Britanie (Anglie). Nemecko = DL, Recko = SV, Gruzie = 4L.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-037",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktery prefix oznacuje Wales?",
    choices: [
      { id: "a", text: "GW" },
      { id: "b", text: "GM" },
      { id: "c", text: "GI" },
      { id: "d", text: "G" },
    ],
    correctChoiceId: "a",
    explanation:
      "GW = Wales, GM = Skotsko, GI = Severni Irsko, G = Anglie. Vsechny jsou soucasti Velke Britanie.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-038",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktery prefix oznacuje Skotsko?",
    choices: [
      { id: "a", text: "GM" },
      { id: "b", text: "GW" },
      { id: "c", text: "GI" },
      { id: "d", text: "SM" },
    ],
    correctChoiceId: "a",
    explanation:
      "GM = Skotsko. GW = Wales, GI = Severni Irsko, SM = Svedsko.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-039",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix EA?",
    choices: [
      { id: "a", text: "Spanelsko" },
      { id: "b", text: "Estonsko" },
      { id: "c", text: "Egypt" },
      { id: "d", text: "Ekvador" },
    ],
    correctChoiceId: "a",
    explanation:
      "EA = Spanelsko (Espana). Estonsko = ES, Egypt = SU, Ekvador = HC.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-040",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix PA?",
    choices: [
      { id: "a", text: "Nizozemsko" },
      { id: "b", text: "Panama" },
      { id: "c", text: "Pakistam" },
      { id: "d", text: "Polsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "PA = Nizozemsko (Pays-Bas). Panama = HP, Pakistan = AP, Polsko = SP.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-041",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix ON?",
    choices: [
      { id: "a", text: "Belgie" },
      { id: "b", text: "Norsko" },
      { id: "c", text: "Nizozemsko" },
      { id: "d", text: "Oman" },
    ],
    correctChoiceId: "a",
    explanation:
      "ON = Belgie. Norsko = LA, Nizozemsko = PA, Oman = A4.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-042",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix SM?",
    choices: [
      { id: "a", text: "Svedsko" },
      { id: "b", text: "Skotsko" },
      { id: "c", text: "Slovinsko" },
      { id: "d", text: "Svycarsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "SM = Svedsko. Skotsko = GM, Slovinsko = S5, Svycarsko = HB9.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-043",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix LA?",
    choices: [
      { id: "a", text: "Norsko" },
      { id: "b", text: "Lotyssko" },
      { id: "c", text: "Litva" },
      { id: "d", text: "Lucembursko" },
    ],
    correctChoiceId: "a",
    explanation:
      "LA = Norsko. Lotyssko = YL, Litva = LY, Lucembursko = LX.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-044",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix OH?",
    choices: [
      { id: "a", text: "Finsko" },
      { id: "b", text: "Madarsko" },
      { id: "c", text: "Rakousko" },
      { id: "d", text: "Norsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "OH = Finsko. Madarsko = HA, Rakousko = OE, Norsko = LA.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-045",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix UA?",
    choices: [
      { id: "a", text: "Rusko" },
      { id: "b", text: "Ukrajina" },
      { id: "c", text: "USA" },
      { id: "d", text: "Uruguay" },
    ],
    correctChoiceId: "a",
    explanation:
      "UA = Rusko. Ukrajina = UR/UT/UU, USA = W/K/N, Uruguay = CX.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-046",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix LZ?",
    choices: [
      { id: "a", text: "Bulharsko" },
      { id: "b", text: "Lucembursko" },
      { id: "c", text: "Lotyssko" },
      { id: "d", text: "Litva" },
    ],
    correctChoiceId: "a",
    explanation:
      "LZ = Bulharsko. Lucembursko = LX, Lotyssko = YL, Litva = LY.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-047",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix YO?",
    choices: [
      { id: "a", text: "Rumunsko" },
      { id: "b", text: "Srbsko" },
      { id: "c", text: "Recko" },
      { id: "d", text: "Chorvatsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "YO = Rumunsko. Srbsko = YU, Recko = SV, Chorvatsko = 9A.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-048",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix 9A?",
    choices: [
      { id: "a", text: "Chorvatsko" },
      { id: "b", text: "Srbsko" },
      { id: "c", text: "Bosna a Hercegovina" },
      { id: "d", text: "Cerna Hora" },
    ],
    correctChoiceId: "a",
    explanation:
      "9A = Chorvatsko. Srbsko = YU, Bosna a Hercegovina = E7, Cerna Hora = 4O.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-049",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix S5?",
    choices: [
      { id: "a", text: "Slovinsko" },
      { id: "b", text: "Slovensko" },
      { id: "c", text: "Svedsko" },
      { id: "d", text: "Srbsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "S5 = Slovinsko. Slovensko = OM, Svedsko = SM, Srbsko = YU.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-050",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix HB9?",
    choices: [
      { id: "a", text: "Svycarsko" },
      { id: "b", text: "Madarsko" },
      { id: "c", text: "Belgie" },
      { id: "d", text: "Lichtenstejnsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "HB9 = Svycarsko. Madarsko = HA, Belgie = ON. Lichtenstejnsko pouziva HB0.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-051",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix CT?",
    choices: [
      { id: "a", text: "Portugalsko" },
      { id: "b", text: "Chorvatsko" },
      { id: "c", text: "Kypr" },
      { id: "d", text: "Kanada" },
    ],
    correctChoiceId: "a",
    explanation:
      "CT = Portugalsko. Chorvatsko = 9A, Kypr = 5B, Kanada = VE.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-052",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix SV?",
    choices: [
      { id: "a", text: "Recko" },
      { id: "b", text: "Svedsko" },
      { id: "c", text: "Slovinsko" },
      { id: "d", text: "Slovensko" },
    ],
    correctChoiceId: "a",
    explanation:
      "SV = Recko. Svedsko = SM, Slovinsko = S5, Slovensko = OM.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-053",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix YU?",
    choices: [
      { id: "a", text: "Srbsko" },
      { id: "b", text: "Rumunsko" },
      { id: "c", text: "Chorvatsko" },
      { id: "d", text: "Bulharsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "YU = Srbsko (puvodni prefix cele Jugoslavie). Rumunsko = YO, Chorvatsko = 9A, Bulharsko = LZ.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-054",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jaky prefix ma Nemecko krome DL?",
    choices: [
      { id: "a", text: "DA az DR (cely blok)" },
      { id: "b", text: "DE az DF" },
      { id: "c", text: "Pouze DL" },
      { id: "d", text: "GL a GM" },
    ],
    correctChoiceId: "a",
    explanation:
      "Nemecko ma prideleny blok DA az DR, protoze ma nejvetsi radioamaterskou komunitu v Evrope. Nejbeznejsi je DL. GM = Skotsko.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-055",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktery prefix oznacuje Severni Irsko?",
    choices: [
      { id: "a", text: "GI" },
      { id: "b", text: "EI" },
      { id: "c", text: "GM" },
      { id: "d", text: "GW" },
    ],
    correctChoiceId: "a",
    explanation:
      "GI = Severni Irsko (soucast Velke Britanie). EI = Irska republika (samostatny stat), GM = Skotsko, GW = Wales.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-056",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jaky prefix ma Dansko?",
    choices: [
      { id: "a", text: "OZ" },
      { id: "b", text: "DK" },
      { id: "c", text: "DA" },
      { id: "d", text: "SM" },
    ],
    correctChoiceId: "a",
    explanation:
      "OZ = Dansko. DK neni radioamatersky prefix. DA je soucasti nemeckeho bloku. SM = Svedsko.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-057",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jaky prefix ma Lucembursko?",
    choices: [
      { id: "a", text: "LX" },
      { id: "b", text: "LU" },
      { id: "c", text: "LA" },
      { id: "d", text: "LZ" },
    ],
    correctChoiceId: "a",
    explanation:
      "LX = Lucembursko. LU = Argentina, LA = Norsko, LZ = Bulharsko.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },

  // -----------------------------------------------------------------------
  // World prefixes & ITU regions (prefixes-03)
  // O-PRF-058 to O-PRF-085
  // -----------------------------------------------------------------------
  {
    id: "O-PRF-058",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Kolik ITU regionu existuje?",
    choices: [
      { id: "a", text: "3" },
      { id: "b", text: "4" },
      { id: "c", text: "5" },
      { id: "d", text: "6" },
    ],
    correctChoiceId: "a",
    explanation:
      "ITU rozdeluje svet do 3 regionu: Region 1 (Evropa, Afrika), Region 2 (Amerika), Region 3 (Asie, Pacifik).",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-059",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Do ktereho ITU regionu patri Ceska republika?",
    choices: [
      { id: "a", text: "Region 1" },
      { id: "b", text: "Region 2" },
      { id: "c", text: "Region 3" },
      { id: "d", text: "Region 4" },
    ],
    correctChoiceId: "a",
    explanation:
      "Ceska republika lezi v Evrope, ktera patri do ITU Regionu 1. Region 4 neexistuje.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-060",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co zahrnuje ITU Region 1?",
    choices: [
      { id: "a", text: "Evropu a Afriku" },
      { id: "b", text: "Ameriku" },
      { id: "c", text: "Asii a Pacifik" },
      { id: "d", text: "Pouze Evropu" },
    ],
    correctChoiceId: "a",
    explanation:
      "Region 1 = Evropa a Afrika. Region 2 = Amerika. Region 3 = Asie a Pacifik. Evropa neni samostatny region.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-061",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co zahrnuje ITU Region 2?",
    choices: [
      { id: "a", text: "Ameriku (Severnim i Jizni)" },
      { id: "b", text: "Evropu a Afriku" },
      { id: "c", text: "Asii a Pacifik" },
      { id: "d", text: "Pouze Severnim Ameriku" },
    ],
    correctChoiceId: "a",
    explanation:
      "Region 2 zahrnuje celou Ameriku - Severnim i Jizni. Region 1 = Evropa+Afrika, Region 3 = Asie+Pacifik.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-062",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co zahrnuje ITU Region 3?",
    choices: [
      { id: "a", text: "Asii a Pacifik" },
      { id: "b", text: "Ameriku" },
      { id: "c", text: "Evropu a Afriku" },
      { id: "d", text: "Pouze Australii" },
    ],
    correctChoiceId: "a",
    explanation:
      "Region 3 = Asie a Pacifik (vcetne Australie, Noveho Zelandu, Japonska atd.).",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-063",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktery prefix oznacuje USA?",
    choices: [
      { id: "a", text: "W" },
      { id: "b", text: "US" },
      { id: "c", text: "UA" },
      { id: "d", text: "AM" },
    ],
    correctChoiceId: "a",
    explanation:
      "W (take K a N) = USA. US neni radioamatersky prefix. UA = Rusko. AM neni prefix.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-064",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktery prefix oznacuje Kanadu?",
    choices: [
      { id: "a", text: "VE" },
      { id: "b", text: "CA" },
      { id: "c", text: "CQ" },
      { id: "d", text: "VK" },
    ],
    correctChoiceId: "a",
    explanation:
      "VE = Kanada. CA neni radioamatersky prefix. CQ je vseobecna vyzva, ne prefix. VK = Australie.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-065",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix PY?",
    choices: [
      { id: "a", text: "Brazilie" },
      { id: "b", text: "Paraguay" },
      { id: "c", text: "Peru" },
      { id: "d", text: "Panama" },
    ],
    correctChoiceId: "a",
    explanation:
      "PY = Brazilie. Paraguay = ZP, Peru = OA, Panama = HP.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-066",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix JA?",
    choices: [
      { id: "a", text: "Japonsko" },
      { id: "b", text: "Jamajka" },
      { id: "c", text: "Jordansko" },
      { id: "d", text: "Jizni Korea" },
    ],
    correctChoiceId: "a",
    explanation:
      "JA = Japonsko. Jamajka = 6Y, Jordansko = JY, Jizni Korea = HL.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-067",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix VK?",
    choices: [
      { id: "a", text: "Australie" },
      { id: "b", text: "Kanada" },
      { id: "c", text: "Novy Zeland" },
      { id: "d", text: "Indie" },
    ],
    correctChoiceId: "a",
    explanation:
      "VK = Australie. Kanada = VE, Novy Zeland = ZL, Indie = VU.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-068",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix ZL?",
    choices: [
      { id: "a", text: "Novy Zeland" },
      { id: "b", text: "Jizni Afrika" },
      { id: "c", text: "Zambie" },
      { id: "d", text: "Zimbabwe" },
    ],
    correctChoiceId: "a",
    explanation:
      "ZL = Novy Zeland. Jizni Afrika = ZS, Zambie = 9J, Zimbabwe = Z2.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-069",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix VU?",
    choices: [
      { id: "a", text: "Indie" },
      { id: "b", text: "Vietnam" },
      { id: "c", text: "Venezuela" },
      { id: "d", text: "Kanada" },
    ],
    correctChoiceId: "a",
    explanation:
      "VU = Indie. Vietnam = XV/3W, Venezuela = YV, Kanada = VE.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-070",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix HL?",
    choices: [
      { id: "a", text: "Jizni Korea" },
      { id: "b", text: "Japonsko" },
      { id: "c", text: "Cina" },
      { id: "d", text: "Hongkong" },
    ],
    correctChoiceId: "a",
    explanation:
      "HL = Jizni Korea. Japonsko = JA, Cina = BY, Hongkong = VR.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-071",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix BY?",
    choices: [
      { id: "a", text: "Cina" },
      { id: "b", text: "Belorusko" },
      { id: "c", text: "Barma (Myanmar)" },
      { id: "d", text: "Bulharsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "BY = Cina. Belorusko = EU/EW, Barma/Myanmar = XZ, Bulharsko = LZ.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-072",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix 4X?",
    choices: [
      { id: "a", text: "Izrael" },
      { id: "b", text: "Jordansko" },
      { id: "c", text: "Iraky" },
      { id: "d", text: "Iran" },
    ],
    correctChoiceId: "a",
    explanation:
      "4X = Izrael. Jordansko = JY, Iraky = YI, Iran = EP.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-073",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix ZS?",
    choices: [
      { id: "a", text: "Jizni Afrika" },
      { id: "b", text: "Novy Zeland" },
      { id: "c", text: "Zambie" },
      { id: "d", text: "Zimbabwe" },
    ],
    correctChoiceId: "a",
    explanation:
      "ZS = Jizni Afrika. Novy Zeland = ZL, Zambie = 9J, Zimbabwe = Z2.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-074",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix A4?",
    choices: [
      { id: "a", text: "Oman" },
      { id: "b", text: "Spojene arabske emiraty" },
      { id: "c", text: "Saudska Arabie" },
      { id: "d", text: "Katar" },
    ],
    correctChoiceId: "a",
    explanation:
      "A4 = Oman. Spojene arabske emiraty = A6, Saudska Arabie = HZ, Katar = A7.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-075",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix 5B?",
    choices: [
      { id: "a", text: "Kypr" },
      { id: "b", text: "Recko" },
      { id: "c", text: "Malta" },
      { id: "d", text: "Turecko" },
    ],
    correctChoiceId: "a",
    explanation:
      "5B = Kypr. Recko = SV, Malta = 9H, Turecko = TA.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-076",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix SU?",
    choices: [
      { id: "a", text: "Egypt" },
      { id: "b", text: "Sudan" },
      { id: "c", text: "Svedsko" },
      { id: "d", text: "Surinam" },
    ],
    correctChoiceId: "a",
    explanation:
      "SU = Egypt. Sudan = ST, Svedsko = SM, Surinam = PZ.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-077",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Do ktereho ITU regionu patri Japonsko?",
    choices: [
      { id: "a", text: "Region 3" },
      { id: "b", text: "Region 1" },
      { id: "c", text: "Region 2" },
      { id: "d", text: "Region 4" },
    ],
    correctChoiceId: "a",
    explanation:
      "Japonsko lezi v Asii, ktera patri do ITU Regionu 3 (Asie a Pacifik). Region 4 neexistuje.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-078",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Do ktereho ITU regionu patri Brazilie?",
    choices: [
      { id: "a", text: "Region 2" },
      { id: "b", text: "Region 1" },
      { id: "c", text: "Region 3" },
      { id: "d", text: "Region 4" },
    ],
    correctChoiceId: "a",
    explanation:
      "Brazilie lezi v Jizni Americe, ktera patri do ITU Regionu 2 (cela Amerika).",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-079",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Do ktereho ITU regionu patri Jizni Afrika?",
    choices: [
      { id: "a", text: "Region 1" },
      { id: "b", text: "Region 2" },
      { id: "c", text: "Region 3" },
      { id: "d", text: "Region 4" },
    ],
    correctChoiceId: "a",
    explanation:
      "Jizni Afrika je v Africe, ktera patri do ITU Regionu 1 (Evropa a Afrika).",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-080",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktery prefix pouzivaji USA krome W?",
    choices: [
      { id: "a", text: "K a N" },
      { id: "b", text: "U a V" },
      { id: "c", text: "A a B" },
      { id: "d", text: "X a Y" },
    ],
    correctChoiceId: "a",
    explanation:
      "USA ma prefixy W, K, N a dale blok AA-AL. K a N jsou nejbeznejsi vedle W.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-081",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix LU?",
    choices: [
      { id: "a", text: "Argentina" },
      { id: "b", text: "Lucembursko" },
      { id: "c", text: "Litva" },
      { id: "d", text: "Lotyssko" },
    ],
    correctChoiceId: "a",
    explanation:
      "LU = Argentina. Lucembursko = LX, Litva = LY, Lotyssko = YL.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-082",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera zeme pouziva prefix CE?",
    choices: [
      { id: "a", text: "Chile" },
      { id: "b", text: "Kolumbie" },
      { id: "c", text: "Kostarika" },
      { id: "d", text: "Kuba" },
    ],
    correctChoiceId: "a",
    explanation:
      "CE = Chile. Kolumbie = HK, Kostarika = TI, Kuba = CO.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-083",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Do ktereho ITU regionu patri Australie?",
    choices: [
      { id: "a", text: "Region 3" },
      { id: "b", text: "Region 1" },
      { id: "c", text: "Region 2" },
      { id: "d", text: "Nema prirazeny region" },
    ],
    correctChoiceId: "a",
    explanation:
      "Australie patri do ITU Regionu 3 (Asie a Pacifik). Kazda zeme ma prirazeny region.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-084",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Ktera organizace rozdelila svet do tri frekvencnich regionu?",
    choices: [
      { id: "a", text: "ITU (Mezinarodni telekomunikacni unie)" },
      { id: "b", text: "IARU (Mezinarodni radioamaterskam unie)" },
      { id: "c", text: "NATO" },
      { id: "d", text: "Evropska unie" },
    ],
    correctChoiceId: "a",
    explanation:
      "ITU rozdelila svet do 3 regionu pro spravu frekvencniho spektra. IARU je radioamaterskam organizace, ale nerozhoduje o regionech.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-085",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Proc ma USA prideleno vice radioamaterskych prefixu (W, K, N, AA-AL)?",
    choices: [
      { id: "a", text: "Ma nejvetsi pocet radioamateru na svete" },
      { id: "b", text: "Je nejvetsi zeme na svete" },
      { id: "c", text: "Byla zakladajicim clenem ITU" },
      { id: "d", text: "Pouziva jiny system znacek" },
    ],
    correctChoiceId: "a",
    explanation:
      "USA ma pres 750 000 licencovanych radioamateru, coz je nejvice na svete. Jeden prefix by nestacil pro tak velky pocet znacek.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
];
