import type { Question } from "@/lib/types";

export const operatingPrefixesQuestions: Question[] = [
  // -----------------------------------------------------------------------
  // Callsign structure, OK/OL, portable/mobile (prefixes-01)
  // O-PRF-001 to O-PRF-028
  // -----------------------------------------------------------------------
  {
    id: "O-PRF-001",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Z jakých části se sklada radioamaterskam volací značka?",
    choices: [
      { id: "a", text: "Prefix, cislice, suffix" },
      { id: "b", text: "Prefix, suffix, lomitko" },
      { id: "c", text: "Zeme, mesto, jmeno" },
      { id: "d", text: "Region, frekvence, cislo" },
    ],
    correctChoiceId: "a",
    explanation:
      "Volaci značka ma tři části: prefix (země), číslice (oblast/kategorie) a suffix (unikátní označení). Lomitko není soucast základní struktury.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-002",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co označuje prefix ve volací značce?",
    choices: [
      { id: "a", text: "Zemi, ve ktere je stanice registrovana" },
      { id: "b", text: "Oblast v ramci zeme" },
      { id: "c", text: "Typ vysildace" },
      { id: "d", text: "Frekvencni pasmo" },
    ],
    correctChoiceId: "a",
    explanation:
      "Prefix určuje zemí registrace stanice. Oblast se označuje cislici za prefixem. Typ vysílače ani pásmo se z volací značky neurčí.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-003",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jake prefixy používá Česká republika?",
    choices: [
      { id: "a", text: "OK a OL" },
      { id: "b", text: "OK a OM" },
      { id: "c", text: "CZ a OK" },
      { id: "d", text: "OL a OM" },
    ],
    correctChoiceId: "a",
    explanation:
      "Česká republika ma prefixy OK (tradiční) a OL (dodatečný blok). OM je Slovensko, CZ není radioamatérský prefix.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-004",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jaky je prefix ve volací značce OK1ABC?",
    choices: [
      { id: "a", text: "OK" },
      { id: "b", text: "OK1" },
      { id: "c", text: "O" },
      { id: "d", text: "OK1A" },
    ],
    correctChoiceId: "a",
    explanation:
      "Prefix je část pred cislici - tedy OK. Cislice 1 není součástí prefixu, odděluje prefix od suffixu.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-005",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co označuje číslice ve volací značce OK2XYZ?",
    choices: [
      { id: "a", text: "Oblast nebo kategorii v ramci zeme" },
      { id: "b", text: "Pocet operatoru na stanici" },
      { id: "c", text: "Rok ziskani licence" },
      { id: "d", text: "Vykonovou tridu" },
    ],
    correctChoiceId: "a",
    explanation:
      "Cislice za prefixem označuje oblast ci kategorii (například okres). Nema nic společného s počtem operátorů ani rokem licence.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-006",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co znamená označení /P za volací značkou?",
    choices: [
      { id: "a", text: "Přenosná stanice (portable)" },
      { id: "b", text: "Mobilní stanice" },
      { id: "c", text: "Námořní mobilní stanice" },
      { id: "d", text: "Stanice v zahranici" },
    ],
    correctChoiceId: "a",
    explanation:
      "/P = portable (přenosná). /M = mobile (mobilní), /MM = maritime mobile (námořní). Provoz ze zahraničí se označuje prefixem hostitelské země.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-007",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co znamená označení /M za volací značkou?",
    choices: [
      { id: "a", text: "Mobilní stanice" },
      { id: "b", text: "Přenosná stanice" },
      { id: "c", text: "Námořní mobilní stanice" },
      { id: "d", text: "Letecká mobilní stanice" },
    ],
    correctChoiceId: "a",
    explanation:
      "/M = mobile (mobilní, například z automobilu). /P = portable, /MM = maritime mobile, /AM = aeronautical mobile.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-008",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co znamená označení /MM za volací značkou?",
    choices: [
      { id: "a", text: "Námořní mobilní stanice (maritime mobile)" },
      { id: "b", text: "Dvojitá mobilní stanice" },
      { id: "c", text: "Mobilní stanice s velkym vykonem" },
      { id: "d", text: "Přenosná stanice na hore" },
    ],
    correctChoiceId: "a",
    explanation:
      "/MM = maritime mobile, provoz z lode na mori. Nejedna se o zdvojený suffix /M.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-009",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Odkud vysílá stanice OE/OK1ABC?",
    choices: [
      { id: "a", text: "Z Rakouska" },
      { id: "b", text: "Z České republiky" },
      { id: "c", text: "Z Nemecka" },
      { id: "d", text: "Ze Slovenska" },
    ],
    correctChoiceId: "a",
    explanation:
      "OE pred lomítkem označuje zemí, ze které stanice vysílá - OE = Rakousko. OK1ABC je domaci značka českého operátora.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-010",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Odkud vysílá stanice SP/OK2DEF?",
    choices: [
      { id: "a", text: "Z Polska" },
      { id: "b", text: "Z České republiky" },
      { id: "c", text: "Ze Slovenska" },
      { id: "d", text: "Ze Spanelska" },
    ],
    correctChoiceId: "a",
    explanation:
      "SP pred lomítkem = stanice vysílá z Polska. OK2DEF je domaci česká značka operátora.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-011",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jak se oznaci český radioamater OK1ABC vysilajici z Nemecka?",
    choices: [
      { id: "a", text: "DL/OK1ABC" },
      { id: "b", text: "OK1ABC/DL" },
      { id: "c", text: "DL-OK1ABC" },
      { id: "d", text: "OK1ABC/D" },
    ],
    correctChoiceId: "a",
    explanation:
      "Prefix hostitelské země se pise pred lomítko a domaci značku: DL/OK1ABC. Poradi je dulezite - prefix hostitelské země je vždy prvni.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-012",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co je suffix ve volací značce OK1ABC?",
    choices: [
      { id: "a", text: "ABC" },
      { id: "b", text: "OK" },
      { id: "c", text: "1ABC" },
      { id: "d", text: "OK1" },
    ],
    correctChoiceId: "a",
    explanation:
      "Suffix je část za cislici - ABC. Unikatne identifikuje konkrétního operátora v ramci dane země a oblasti.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-013",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera volací značka patri české stanici?",
    choices: [
      { id: "a", text: "OL5ABC" },
      { id: "b", text: "OM3ABC" },
      { id: "c", text: "OE1ABC" },
      { id: "d", text: "DL2ABC" },
    ],
    correctChoiceId: "a",
    explanation:
      "OL je český prefix. OM = Slovensko, OE = Rakousko, DL = Německo.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-014",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Kolik pismen může mit suffix volací značky?",
    choices: [
      { id: "a", text: "Jedno az tri" },
      { id: "b", text: "Vzdy presne tri" },
      { id: "c", text: "Vzdy presne dve" },
      { id: "d", text: "Ctyri az pet" },
    ],
    correctChoiceId: "a",
    explanation:
      "Suffix ma jedno az tři písmena. Napriklad OK1A (jedno), OK1AB (dvě) nebo OK1ABC (tři) jsou všechny platne značky.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-015",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co označuje prefix OL?",
    choices: [
      { id: "a", text: "Česká republika" },
      { id: "b", text: "Slovensko" },
      { id: "c", text: "Nizozemsko" },
      { id: "d", text: "Norsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "OL je druhý český prefix vedle OK. Slovensko = OM, Nizozemsko = PA, Norsko = LA.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-016",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jaka je domaci země stanice s volací značkou OM3BCS?",
    choices: [
      { id: "a", text: "Slovensko" },
      { id: "b", text: "Česká republika" },
      { id: "c", text: "Oman" },
      { id: "d", text: "Moldavsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "OM = Slovensko. OK/OL = Česká republika, A4 = Oman, ER = Moldavsko.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-017",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co znamená volací značka OK1ABC/AM?",
    choices: [
      { id: "a", text: "Letecká mobilní stanice (aeronautical mobile)" },
      { id: "b", text: "Stanice v Americe" },
      { id: "c", text: "Amaterska stanice" },
      { id: "d", text: "Automaticky mod" },
    ],
    correctChoiceId: "a",
    explanation:
      "/AM = aeronautical mobile, provoz z letadla. Nesouvisim s Amerikou ani s automatickym módem.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-018",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Stanice vysílá pod značkou HA/OK1ABC. Kde se fyzicky nachazi?",
    choices: [
      { id: "a", text: "V Madarsku" },
      { id: "b", text: "V Ceske republice" },
      { id: "c", text: "V Rakousku" },
      { id: "d", text: "Na Slovensku" },
    ],
    correctChoiceId: "a",
    explanation:
      "HA pred lomítkem = stanice je v Madarsku. OK1ABC je domaci značka českého operátora.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-019",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Ktera část volací značky jednoznačně identifikuje konkrétního operátora?",
    choices: [
      { id: "a", text: "Suffix" },
      { id: "b", text: "Prefix" },
      { id: "c", text: "Cislice" },
      { id: "d", text: "Lomitko" },
    ],
    correctChoiceId: "a",
    explanation:
      "Suffix (písmena za cislici) je unikátní pro kazdeho operátora. Prefix určuje zemí, číslice oblast.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-020",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jaky prefix ma Slovensko?",
    choices: [
      { id: "a", text: "OM" },
      { id: "b", text: "OK" },
      { id: "c", text: "OE" },
      { id: "d", text: "SL" },
    ],
    correctChoiceId: "a",
    explanation:
      "OM = Slovensko. OK = Česká republika, OE = Rakousko. SL není platný radioamatérský prefix.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-021",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jaky prefix ma Rakousko?",
    choices: [
      { id: "a", text: "OE" },
      { id: "b", text: "AU" },
      { id: "c", text: "AT" },
      { id: "d", text: "OM" },
    ],
    correctChoiceId: "a",
    explanation:
      "OE = Rakousko (Oesterreich). AU a AT nejsou radioamatérské prefixy. OM = Slovensko.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-022",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Kdo přiděluje radioamatérské prefixy jednotlivym zemim?",
    choices: [
      { id: "a", text: "ITU (Mezinarodni telekomunikacni unie)" },
      { id: "b", text: "IARU (Mezinarodni radioamaterskam unie)" },
      { id: "c", text: "OSN (Organizace spojenych narodu)" },
      { id: "d", text: "NATO" },
    ],
    correctChoiceId: "a",
    explanation:
      "Prefixy přiděluje ITU. IARU je mezinárodní organizace radioamatérů, ale neprideluje prefixy. OSN a NATO nemaji s prefixy nic společného.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-023",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Cesky radioamater OK1XY vysílá z přenosné stanice v horach. Jakou značku pouzije?",
    choices: [
      { id: "a", text: "OK1XY/P" },
      { id: "b", text: "OK1XY/M" },
      { id: "c", text: "OK1XY/MM" },
      { id: "d", text: "P/OK1XY" },
    ],
    correctChoiceId: "a",
    explanation:
      "/P se pridava za značku pro přenosný provoz. /M je pro mobilní provoz (z vozidla). Oznaceni se vždy pridava za vlastní značku.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-024",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktera volací značka označuje stanici z České republiky?",
    choices: [
      { id: "a", text: "OK3AB" },
      { id: "b", text: "OE5AB" },
      { id: "c", text: "OM7AB" },
      { id: "d", text: "SP9AB" },
    ],
    correctChoiceId: "a",
    explanation:
      "OK = Česká republika. OE = Rakousko, OM = Slovensko, SP = Polsko.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-025",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Jak se od sebe liší prefixy OK a OL?",
    choices: [
      { id: "a", text: "Oba jsou ceske - OK je tradicni, OL je dodatecny blok" },
      { id: "b", text: "OK je Cesko, OL je Slovensko" },
      { id: "c", text: "OK je pro KV, OL pro VHF" },
      { id: "d", text: "OK je pro individualni, OL pro klubove stanice" },
    ],
    correctChoiceId: "a",
    explanation:
      "OK i OL jsou české prefixy. Rozdeleni na pásma nebo typ stanice není správně - oba se používají pro všechny druhý provozu.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-026",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Stanice OK1ABC vysílá z automobilu. Jaky suffix prida?",
    choices: [
      { id: "a", text: "/M" },
      { id: "b", text: "/P" },
      { id: "c", text: "/MM" },
      { id: "d", text: "/AM" },
    ],
    correctChoiceId: "a",
    explanation:
      "/M = mobile (z vozidla). /P = přenosná, /MM = námořní mobilní (z lode), /AM = letecká mobilní.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-027",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Kolik cislicmezi prefixem a suffixem obsahuje standardní volací značka?",
    choices: [
      { id: "a", text: "Jednu" },
      { id: "b", text: "Dve" },
      { id: "c", text: "Zadnou" },
      { id: "d", text: "Tri" },
    ],
    correctChoiceId: "a",
    explanation:
      "Standardni volací značka obsahuje prave jednu cislici mezi prefixem a suffixem, například OK1ABC.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },
  {
    id: "O-PRF-028",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Prefix ve volací značce může obsahovat:",
    choices: [
      { id: "a", text: "Jedno az tri pismena" },
      { id: "b", text: "Vzdy presne dve pismena" },
      { id: "c", text: "Pismena i cislice dohromady" },
      { id: "d", text: "Vzdy jedno pismeno" },
    ],
    correctChoiceId: "a",
    explanation:
      "Prefix ma jedno az tři písmena (například I pro Italii, OK pro Cesko, HB9 vsak obsahuje cislici - to je výjimka u nekterych prefixu). Bezne prefixy jsou jedno az dvoupismenne.",
    relatedLessonIds: ["prefixes-01"],
    tags: ["volaci-znacka", "recall"],
  },

  // -----------------------------------------------------------------------
  // European prefixes (prefixes-02)
  // O-PRF-029 to O-PRF-057
  // -----------------------------------------------------------------------
  {
    id: "O-PRF-029",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix DL?",
    choices: [
      { id: "a", text: "Německo" },
      { id: "b", text: "Dánsko" },
      { id: "c", text: "Nizozemsko" },
      { id: "d", text: "Lucembursko" },
    ],
    correctChoiceId: "a",
    explanation:
      "DL = Německo (Deutschland). Dánsko = OZ, Nizozemsko = PA, Lucembursko = LX.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-030",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix SP?",
    choices: [
      { id: "a", text: "Polsko" },
      { id: "b", text: "Španělsko" },
      { id: "c", text: "Portugalsko" },
      { id: "d", text: "Švédsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "SP = Polsko. Španělsko = EA, Portugalsko = CT, Švédsko = SM.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-031",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix HA?",
    choices: [
      { id: "a", text: "Maďarsko" },
      { id: "b", text: "Chorvatsko" },
      { id: "c", text: "Nizozemsko" },
      { id: "d", text: "Finsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "HA = Maďarsko (Hungary/Magyarorszag). Chorvatsko = 9A, Nizozemsko = PA, Finsko = OH.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-032",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix OE?",
    choices: [
      { id: "a", text: "Rakousko" },
      { id: "b", text: "Česká republika" },
      { id: "c", text: "Slovensko" },
      { id: "d", text: "Norsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "OE = Rakousko (Oesterreich). OK/OL = Cesko, OM = Slovensko, LA = Norsko.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-033",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix OM?",
    choices: [
      { id: "a", text: "Slovensko" },
      { id: "b", text: "Česká republika" },
      { id: "c", text: "Oman" },
      { id: "d", text: "Moldavsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "OM = Slovensko. OK/OL = Česká republika, A4 = Oman, ER = Moldavsko.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-034",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix I?",
    choices: [
      { id: "a", text: "Itálie" },
      { id: "b", text: "Irsko" },
      { id: "c", text: "Island" },
      { id: "d", text: "Izrael" },
    ],
    correctChoiceId: "a",
    explanation:
      "I = Itálie. Irsko = EI, Island = TF, Izrael = 4X.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-035",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix F?",
    choices: [
      { id: "a", text: "Francie" },
      { id: "b", text: "Finsko" },
      { id: "c", text: "Filipiny" },
      { id: "d", text: "Fidzi" },
    ],
    correctChoiceId: "a",
    explanation:
      "F = Francie. Finsko = OH, Filipiny = DU, Fidzi = 3D.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-036",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix G?",
    choices: [
      { id: "a", text: "Velká Británie (Anglie)" },
      { id: "b", text: "Německo" },
      { id: "c", text: "Řecko" },
      { id: "d", text: "Gruzie" },
    ],
    correctChoiceId: "a",
    explanation:
      "G = Velká Británie (Anglie). Německo = DL, Řecko = SV, Gruzie = 4L.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-037",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktery prefix označuje Wales?",
    choices: [
      { id: "a", text: "GW" },
      { id: "b", text: "GM" },
      { id: "c", text: "GI" },
      { id: "d", text: "G" },
    ],
    correctChoiceId: "a",
    explanation:
      "GW = Wales, GM = Skotsko, GI = Severni Irsko, G = Anglie. Vsechny jsou součástí Velke Britanie.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-038",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktery prefix označuje Skotsko?",
    choices: [
      { id: "a", text: "GM" },
      { id: "b", text: "GW" },
      { id: "c", text: "GI" },
      { id: "d", text: "SM" },
    ],
    correctChoiceId: "a",
    explanation:
      "GM = Skotsko. GW = Wales, GI = Severni Irsko, SM = Švédsko.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-039",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix EA?",
    choices: [
      { id: "a", text: "Španělsko" },
      { id: "b", text: "Estonsko" },
      { id: "c", text: "Egypt" },
      { id: "d", text: "Ekvador" },
    ],
    correctChoiceId: "a",
    explanation:
      "EA = Španělsko (Espana). Estonsko = ES, Egypt = SU, Ekvador = HC.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-040",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix PA?",
    choices: [
      { id: "a", text: "Nizozemsko" },
      { id: "b", text: "Panama" },
      { id: "c", text: "Pakistam" },
      { id: "d", text: "Polsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "PA = Nizozemsko (Pays-Bas). Panama = HP, Pakistan = AP, Polsko = SP.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-041",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix ON?",
    choices: [
      { id: "a", text: "Belgie" },
      { id: "b", text: "Norsko" },
      { id: "c", text: "Nizozemsko" },
      { id: "d", text: "Oman" },
    ],
    correctChoiceId: "a",
    explanation:
      "ON = Belgie. Norsko = LA, Nizozemsko = PA, Oman = A4.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-042",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix SM?",
    choices: [
      { id: "a", text: "Švédsko" },
      { id: "b", text: "Skotsko" },
      { id: "c", text: "Slovinsko" },
      { id: "d", text: "Svycarsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "SM = Švédsko. Skotsko = GM, Slovinsko = S5, Svycarsko = HB9.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-043",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix LA?",
    choices: [
      { id: "a", text: "Norsko" },
      { id: "b", text: "Lotyssko" },
      { id: "c", text: "Litva" },
      { id: "d", text: "Lucembursko" },
    ],
    correctChoiceId: "a",
    explanation:
      "LA = Norsko. Lotyssko = YL, Litva = LY, Lucembursko = LX.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-044",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix OH?",
    choices: [
      { id: "a", text: "Finsko" },
      { id: "b", text: "Maďarsko" },
      { id: "c", text: "Rakousko" },
      { id: "d", text: "Norsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "OH = Finsko. Maďarsko = HA, Rakousko = OE, Norsko = LA.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-045",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix UA?",
    choices: [
      { id: "a", text: "Rusko" },
      { id: "b", text: "Ukrajina" },
      { id: "c", text: "USA" },
      { id: "d", text: "Uruguay" },
    ],
    correctChoiceId: "a",
    explanation:
      "UA = Rusko. Ukrajina = UR/UT/UU, USA = W/K/N, Uruguay = CX.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-046",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix LZ?",
    choices: [
      { id: "a", text: "Bulharsko" },
      { id: "b", text: "Lucembursko" },
      { id: "c", text: "Lotyssko" },
      { id: "d", text: "Litva" },
    ],
    correctChoiceId: "a",
    explanation:
      "LZ = Bulharsko. Lucembursko = LX, Lotyssko = YL, Litva = LY.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-047",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix YO?",
    choices: [
      { id: "a", text: "Rumunsko" },
      { id: "b", text: "Srbsko" },
      { id: "c", text: "Řecko" },
      { id: "d", text: "Chorvatsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "YO = Rumunsko. Srbsko = YU, Řecko = SV, Chorvatsko = 9A.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-048",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix 9A?",
    choices: [
      { id: "a", text: "Chorvatsko" },
      { id: "b", text: "Srbsko" },
      { id: "c", text: "Bosna a Hercegovina" },
      { id: "d", text: "Cerna Hora" },
    ],
    correctChoiceId: "a",
    explanation:
      "9A = Chorvatsko. Srbsko = YU, Bosna a Hercegovina = E7, Cerna Hora = 4O.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-049",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix S5?",
    choices: [
      { id: "a", text: "Slovinsko" },
      { id: "b", text: "Slovensko" },
      { id: "c", text: "Švédsko" },
      { id: "d", text: "Srbsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "S5 = Slovinsko. Slovensko = OM, Švédsko = SM, Srbsko = YU.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-050",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix HB9?",
    choices: [
      { id: "a", text: "Svycarsko" },
      { id: "b", text: "Maďarsko" },
      { id: "c", text: "Belgie" },
      { id: "d", text: "Lichtenstejnsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "HB9 = Svycarsko. Maďarsko = HA, Belgie = ON. Lichtenstejnsko používá HB0.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-051",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix CT?",
    choices: [
      { id: "a", text: "Portugalsko" },
      { id: "b", text: "Chorvatsko" },
      { id: "c", text: "Kypr" },
      { id: "d", text: "Kanada" },
    ],
    correctChoiceId: "a",
    explanation:
      "CT = Portugalsko. Chorvatsko = 9A, Kypr = 5B, Kanada = VE.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-052",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix SV?",
    choices: [
      { id: "a", text: "Řecko" },
      { id: "b", text: "Švédsko" },
      { id: "c", text: "Slovinsko" },
      { id: "d", text: "Slovensko" },
    ],
    correctChoiceId: "a",
    explanation:
      "SV = Řecko. Švédsko = SM, Slovinsko = S5, Slovensko = OM.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-053",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix YU?",
    choices: [
      { id: "a", text: "Srbsko" },
      { id: "b", text: "Rumunsko" },
      { id: "c", text: "Chorvatsko" },
      { id: "d", text: "Bulharsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "YU = Srbsko (puvodni prefix cele Jugoslavie). Rumunsko = YO, Chorvatsko = 9A, Bulharsko = LZ.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-054",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jaky prefix ma Německo krome DL?",
    choices: [
      { id: "a", text: "DA az DR (cely blok)" },
      { id: "b", text: "DE az DF" },
      { id: "c", text: "Pouze DL" },
      { id: "d", text: "GL a GM" },
    ],
    correctChoiceId: "a",
    explanation:
      "Německo ma přiděleny blok DA az DR, protoze ma nejvetsi radioamatérskou komunitu v Evrope. Nejbeznejsi je DL. GM = Skotsko.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-055",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktery prefix označuje Severni Irsko?",
    choices: [
      { id: "a", text: "GI" },
      { id: "b", text: "EI" },
      { id: "c", text: "GM" },
      { id: "d", text: "GW" },
    ],
    correctChoiceId: "a",
    explanation:
      "GI = Severni Irsko (soucast Velke Britanie). EI = Irska republika (samostatny stát), GM = Skotsko, GW = Wales.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-056",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jaky prefix ma Dánsko?",
    choices: [
      { id: "a", text: "OZ" },
      { id: "b", text: "DK" },
      { id: "c", text: "DA" },
      { id: "d", text: "SM" },
    ],
    correctChoiceId: "a",
    explanation:
      "OZ = Dánsko. DK není radioamatérský prefix. DA je součástí německého bloků. SM = Švédsko.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },
  {
    id: "O-PRF-057",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Jaky prefix ma Lucembursko?",
    choices: [
      { id: "a", text: "LX" },
      { id: "b", text: "LU" },
      { id: "c", text: "LA" },
      { id: "d", text: "LZ" },
    ],
    correctChoiceId: "a",
    explanation:
      "LX = Lucembursko. LU = Argentina, LA = Norsko, LZ = Bulharsko.",
    relatedLessonIds: ["prefixes-02"],
    tags: ["evropske-prefixy", "recall"],
  },

  // -----------------------------------------------------------------------
  // World prefixes & ITU regions (prefixes-03)
  // O-PRF-058 to O-PRF-085
  // -----------------------------------------------------------------------
  {
    id: "O-PRF-058",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Kolik ITU regionu existuje?",
    choices: [
      { id: "a", text: "3" },
      { id: "b", text: "4" },
      { id: "c", text: "5" },
      { id: "d", text: "6" },
    ],
    correctChoiceId: "a",
    explanation:
      "ITU rozdeluje svet do 3 regionu: Region 1 (Evropa, Afrika), Region 2 (Amerika), Region 3 (Asie, Pacifik).",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-059",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Do kterého ITU regionu patri Česká republika?",
    choices: [
      { id: "a", text: "Region 1" },
      { id: "b", text: "Region 2" },
      { id: "c", text: "Region 3" },
      { id: "d", text: "Region 4" },
    ],
    correctChoiceId: "a",
    explanation:
      "Česká republika lezi v Evrope, která patri do ITU Regionu 1. Region 4 neexistuje.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-060",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co zahrnuje ITU Region 1?",
    choices: [
      { id: "a", text: "Evropu a Afriku" },
      { id: "b", text: "Ameriku" },
      { id: "c", text: "Asii a Pacifik" },
      { id: "d", text: "Pouze Evropu" },
    ],
    correctChoiceId: "a",
    explanation:
      "Region 1 = Evropa a Afrika. Region 2 = Amerika. Region 3 = Asie a Pacifik. Evropa není samostatny region.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-061",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co zahrnuje ITU Region 2?",
    choices: [
      { id: "a", text: "Ameriku (Severnim i Jizni)" },
      { id: "b", text: "Evropu a Afriku" },
      { id: "c", text: "Asii a Pacifik" },
      { id: "d", text: "Pouze Severnim Ameriku" },
    ],
    correctChoiceId: "a",
    explanation:
      "Region 2 zahrnuje celou Ameriku - Severnim i Jizni. Region 1 = Evropa+Afrika, Region 3 = Asie+Pacifik.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-062",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Co zahrnuje ITU Region 3?",
    choices: [
      { id: "a", text: "Asii a Pacifik" },
      { id: "b", text: "Ameriku" },
      { id: "c", text: "Evropu a Afriku" },
      { id: "d", text: "Pouze Australii" },
    ],
    correctChoiceId: "a",
    explanation:
      "Region 3 = Asie a Pacifik (včetně Australie, Noveho Zelandu, Japonska atd.).",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-063",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktery prefix označuje USA?",
    choices: [
      { id: "a", text: "W" },
      { id: "b", text: "US" },
      { id: "c", text: "UA" },
      { id: "d", text: "AM" },
    ],
    correctChoiceId: "a",
    explanation:
      "W (take K a N) = USA. US není radioamatérský prefix. UA = Rusko. AM není prefix.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-064",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktery prefix označuje Kanadu?",
    choices: [
      { id: "a", text: "VE" },
      { id: "b", text: "CA" },
      { id: "c", text: "CQ" },
      { id: "d", text: "VK" },
    ],
    correctChoiceId: "a",
    explanation:
      "VE = Kanada. CA není radioamatérský prefix. CQ je vseobecna výzva, ne prefix. VK = Australie.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-065",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix PY?",
    choices: [
      { id: "a", text: "Brazilie" },
      { id: "b", text: "Paraguay" },
      { id: "c", text: "Peru" },
      { id: "d", text: "Panama" },
    ],
    correctChoiceId: "a",
    explanation:
      "PY = Brazilie. Paraguay = ZP, Peru = OA, Panama = HP.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-066",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix JA?",
    choices: [
      { id: "a", text: "Japonsko" },
      { id: "b", text: "Jamajka" },
      { id: "c", text: "Jordansko" },
      { id: "d", text: "Jizni Korea" },
    ],
    correctChoiceId: "a",
    explanation:
      "JA = Japonsko. Jamajka = 6Y, Jordansko = JY, Jizni Korea = HL.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-067",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix VK?",
    choices: [
      { id: "a", text: "Australie" },
      { id: "b", text: "Kanada" },
      { id: "c", text: "Novy Zeland" },
      { id: "d", text: "Indie" },
    ],
    correctChoiceId: "a",
    explanation:
      "VK = Australie. Kanada = VE, Novy Zeland = ZL, Indie = VU.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-068",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix ZL?",
    choices: [
      { id: "a", text: "Novy Zeland" },
      { id: "b", text: "Jizni Afrika" },
      { id: "c", text: "Zambie" },
      { id: "d", text: "Zimbabwe" },
    ],
    correctChoiceId: "a",
    explanation:
      "ZL = Novy Zeland. Jizni Afrika = ZS, Zambie = 9J, Zimbabwe = Z2.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-069",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix VU?",
    choices: [
      { id: "a", text: "Indie" },
      { id: "b", text: "Vietnam" },
      { id: "c", text: "Venezuela" },
      { id: "d", text: "Kanada" },
    ],
    correctChoiceId: "a",
    explanation:
      "VU = Indie. Vietnam = XV/3W, Venezuela = YV, Kanada = VE.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-070",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix HL?",
    choices: [
      { id: "a", text: "Jizni Korea" },
      { id: "b", text: "Japonsko" },
      { id: "c", text: "Cina" },
      { id: "d", text: "Hongkong" },
    ],
    correctChoiceId: "a",
    explanation:
      "HL = Jizni Korea. Japonsko = JA, Cina = BY, Hongkong = VR.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-071",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix BY?",
    choices: [
      { id: "a", text: "Cina" },
      { id: "b", text: "Belorusko" },
      { id: "c", text: "Barma (Myanmar)" },
      { id: "d", text: "Bulharsko" },
    ],
    correctChoiceId: "a",
    explanation:
      "BY = Cina. Belorusko = EU/EW, Barma/Myanmar = XZ, Bulharsko = LZ.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-072",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix 4X?",
    choices: [
      { id: "a", text: "Izrael" },
      { id: "b", text: "Jordansko" },
      { id: "c", text: "Iraky" },
      { id: "d", text: "Iran" },
    ],
    correctChoiceId: "a",
    explanation:
      "4X = Izrael. Jordansko = JY, Iraky = YI, Iran = EP.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-073",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix ZS?",
    choices: [
      { id: "a", text: "Jizni Afrika" },
      { id: "b", text: "Novy Zeland" },
      { id: "c", text: "Zambie" },
      { id: "d", text: "Zimbabwe" },
    ],
    correctChoiceId: "a",
    explanation:
      "ZS = Jizni Afrika. Novy Zeland = ZL, Zambie = 9J, Zimbabwe = Z2.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-074",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix A4?",
    choices: [
      { id: "a", text: "Oman" },
      { id: "b", text: "Spojene arabske emiraty" },
      { id: "c", text: "Saudska Arabie" },
      { id: "d", text: "Katar" },
    ],
    correctChoiceId: "a",
    explanation:
      "A4 = Oman. Spojene arabske emiraty = A6, Saudska Arabie = HZ, Katar = A7.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-075",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix 5B?",
    choices: [
      { id: "a", text: "Kypr" },
      { id: "b", text: "Řecko" },
      { id: "c", text: "Malta" },
      { id: "d", text: "Turecko" },
    ],
    correctChoiceId: "a",
    explanation:
      "5B = Kypr. Řecko = SV, Malta = 9H, Turecko = TA.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-076",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix SU?",
    choices: [
      { id: "a", text: "Egypt" },
      { id: "b", text: "Sudan" },
      { id: "c", text: "Švédsko" },
      { id: "d", text: "Surinam" },
    ],
    correctChoiceId: "a",
    explanation:
      "SU = Egypt. Sudan = ST, Švédsko = SM, Surinam = PZ.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-077",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Do kterého ITU regionu patri Japonsko?",
    choices: [
      { id: "a", text: "Region 3" },
      { id: "b", text: "Region 1" },
      { id: "c", text: "Region 2" },
      { id: "d", text: "Region 4" },
    ],
    correctChoiceId: "a",
    explanation:
      "Japonsko lezi v Asii, která patri do ITU Regionu 3 (Asie a Pacifik). Region 4 neexistuje.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-078",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Do kterého ITU regionu patri Brazilie?",
    choices: [
      { id: "a", text: "Region 2" },
      { id: "b", text: "Region 1" },
      { id: "c", text: "Region 3" },
      { id: "d", text: "Region 4" },
    ],
    correctChoiceId: "a",
    explanation:
      "Brazilie lezi v Jizni Americe, která patri do ITU Regionu 2 (cela Amerika).",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-079",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Do kterého ITU regionu patri Jizni Afrika?",
    choices: [
      { id: "a", text: "Region 1" },
      { id: "b", text: "Region 2" },
      { id: "c", text: "Region 3" },
      { id: "d", text: "Region 4" },
    ],
    correctChoiceId: "a",
    explanation:
      "Jizni Afrika je v Africe, která patri do ITU Regionu 1 (Evropa a Afrika).",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-080",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Ktery prefix používají USA krome W?",
    choices: [
      { id: "a", text: "K a N" },
      { id: "b", text: "U a V" },
      { id: "c", text: "A a B" },
      { id: "d", text: "X a Y" },
    ],
    correctChoiceId: "a",
    explanation:
      "USA ma prefixy W, K, N a dále blok AA-AL. K a N jsou nejbeznejsi vedle W.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-081",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix LU?",
    choices: [
      { id: "a", text: "Argentina" },
      { id: "b", text: "Lucembursko" },
      { id: "c", text: "Litva" },
      { id: "d", text: "Lotyssko" },
    ],
    correctChoiceId: "a",
    explanation:
      "LU = Argentina. Lucembursko = LX, Litva = LY, Lotyssko = YL.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-082",
    examPartId: "operating",
    sectionId: "prefixes",
    wording: "Která země používá prefix CE?",
    choices: [
      { id: "a", text: "Chile" },
      { id: "b", text: "Kolumbie" },
      { id: "c", text: "Kostarika" },
      { id: "d", text: "Kuba" },
    ],
    correctChoiceId: "a",
    explanation:
      "CE = Chile. Kolumbie = HK, Kostarika = TI, Kuba = CO.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
  {
    id: "O-PRF-083",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Do kterého ITU regionu patri Australie?",
    choices: [
      { id: "a", text: "Region 3" },
      { id: "b", text: "Region 1" },
      { id: "c", text: "Region 2" },
      { id: "d", text: "Nema prirazeny region" },
    ],
    correctChoiceId: "a",
    explanation:
      "Australie patri do ITU Regionu 3 (Asie a Pacifik). Kazda země ma přiřazeny region.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-084",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Ktera organizace rozdelila svet do tři frekvencnich regionu?",
    choices: [
      { id: "a", text: "ITU (Mezinarodni telekomunikacni unie)" },
      { id: "b", text: "IARU (Mezinarodni radioamaterskam unie)" },
      { id: "c", text: "NATO" },
      { id: "d", text: "Evropska unie" },
    ],
    correctChoiceId: "a",
    explanation:
      "ITU rozdelila svet do 3 regionu pro správu frekvenčního spektra. IARU je radioamaterskam organizace, ale nerozhoduje o regionech.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["itu-regiony", "recall"],
  },
  {
    id: "O-PRF-085",
    examPartId: "operating",
    sectionId: "prefixes",
    wording:
      "Proc ma USA prideleno vice radioamatérských prefixu (W, K, N, AA-AL)?",
    choices: [
      { id: "a", text: "Ma nejvetsi pocet radioamateru na svete" },
      { id: "b", text: "Je nejvetsi zeme na svete" },
      { id: "c", text: "Byla zakladajicim clenem ITU" },
      { id: "d", text: "Pouziva jiny system znacek" },
    ],
    correctChoiceId: "a",
    explanation:
      "USA ma pres 750 000 licencovanych radioamatérů, coz je nejvice na svete. Jeden prefix by nestacil pro tak velky počet značek.",
    relatedLessonIds: ["prefixes-03"],
    tags: ["svetove-prefixy", "recall"],
  },
];
