import type { Question } from "@/lib/types";

export const operatingFrequenciesQuestions: Question[] = [
  // -----------------------------------------------------------------------
  // Band identification (frequencies-01)
  // -----------------------------------------------------------------------
  {
    id: "O-FRQ-001",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Ktere amatérské pásmo lezi v oblasti VHF (30-300 MHz)?",
    choices: [
      { id: "a", text: "2 m (144 MHz)" },
      { id: "b", text: "70 cm (430 MHz)" },
      { id: "c", text: "20 m (14 MHz)" },
      { id: "d", text: "23 cm (1296 MHz)" },
    ],
    correctChoiceId: "a",
    explanation:
      "VHF rozsah je 30-300 MHz. Pasmo 2 m (144 MHz) je jediné amatérské VHF pásmo. 70 cm je UHF, 20 m je HF, 23 cm jsou mikrovlny. Viz slovnik: VHF.",
    relatedLessonIds: ["frequencies-01"],
    tags: ["pasma", "recall"],
  },
  {
    id: "O-FRQ-002",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Jaka frekvence odpovídá pásmu 40 metru?",
    choices: [
      { id: "a", text: "7 MHz" },
      { id: "b", text: "14 MHz" },
      { id: "c", text: "3,5 MHz" },
      { id: "d", text: "21 MHz" },
    ],
    correctChoiceId: "a",
    explanation:
      "lambda = 300/f, tedy f = 300/40 = 7,5 MHz. Pasmo 40 m začíná na 7 MHz. 14 MHz je 20 m, 3,5 MHz je 80 m, 21 MHz je 15 m. Viz vzorec vlnové délky.",
    relatedLessonIds: ["frequencies-01"],
    tags: ["pasma", "apply"],
  },
  {
    id: "O-FRQ-003",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Pasmo 80 metru odpovídá frekvenci přibližně:",
    choices: [
      { id: "a", text: "3,5 MHz" },
      { id: "b", text: "7 MHz" },
      { id: "c", text: "1,8 MHz" },
      { id: "d", text: "14 MHz" },
    ],
    correctChoiceId: "a",
    explanation:
      "f = 300/80 = 3,75 MHz. Pasmo 80 m začíná na 3,5 MHz. 7 MHz je 40 m, 1,8 MHz je 160 m. Viz vzorec vlnové délky.",
    relatedLessonIds: ["frequencies-01"],
    tags: ["pasma", "apply"],
  },
  {
    id: "O-FRQ-004",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Ktere pásmo je označováno jako '20 metru'?",
    choices: [
      { id: "a", text: "Pasmo kolem 14 MHz" },
      { id: "b", text: "Pasmo kolem 7 MHz" },
      { id: "c", text: "Pasmo kolem 21 MHz" },
      { id: "d", text: "Pasmo kolem 28 MHz" },
    ],
    correctChoiceId: "a",
    explanation:
      "300/14 = 21,4 m, zaokrouhlene 20 m. 7 MHz je 40 m, 21 MHz je 15 m, 28 MHz je 10 m. Viz slovnik: amatérská pásma.",
    relatedLessonIds: ["frequencies-01"],
    tags: ["pasma", "recall"],
  },
  {
    id: "O-FRQ-005",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Jaka je přibližná vlnová délka na frekvenci 430 MHz?",
    choices: [
      { id: "a", text: "70 cm" },
      { id: "b", text: "2 m" },
      { id: "c", text: "23 cm" },
      { id: "d", text: "6 m" },
    ],
    correctChoiceId: "a",
    explanation:
      "lambda = 300/430 = 0,70 m = 70 cm. 2 m odpovídá 144 MHz, 23 cm odpovídá 1296 MHz. Viz vzorec vlnové délky.",
    relatedLessonIds: ["frequencies-01"],
    tags: ["vlnova-delka", "apply"],
  },
  {
    id: "O-FRQ-006",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Pasmo 160 metru začíná na frekvenci:",
    choices: [
      { id: "a", text: "1,810 MHz" },
      { id: "b", text: "3,500 MHz" },
      { id: "c", text: "0,136 MHz" },
      { id: "d", text: "7,000 MHz" },
    ],
    correctChoiceId: "a",
    explanation:
      "Pasmo 160 m začíná na 1,810 MHz (1810 kHz). 3,5 MHz je 80 m, 0,136 MHz je pásmo 2200 m, 7 MHz je 40 m. Viz přidělení amatérských pásem.",
    relatedLessonIds: ["frequencies-01"],
    tags: ["pasma", "recall"],
  },
  {
    id: "O-FRQ-007",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Do které kategorie patri pásmo 70 cm (430 MHz)?",
    choices: [
      { id: "a", text: "UHF (Ultra High Frequency)" },
      { id: "b", text: "VHF (Very High Frequency)" },
      { id: "c", text: "HF (High Frequency)" },
      { id: "d", text: "SHF (Super High Frequency)" },
    ],
    correctChoiceId: "a",
    explanation:
      "UHF = 300-3000 MHz. 430 MHz patri do tohoto rozsahu. VHF je 30-300 MHz, HF je 3-30 MHz, SHF je 3-30 GHz. Viz slovnik: UHF.",
    relatedLessonIds: ["frequencies-01"],
    tags: ["pasma", "recall"],
  },
  {
    id: "O-FRQ-008",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Co znamená 'primarne přidělené pásmo'?",
    choices: [
      { id: "a", text: "Radioamateri maji prednost a ochranu pred rusenim od jinych sluzeb" },
      { id: "b", text: "Pasmo je vylucne pro radioamatery" },
      { id: "c", text: "Pasmo lze pouzivat bez povoleni" },
      { id: "d", text: "Pasmo je urceno pouze pro nouzovou komunikaci" },
    ],
    correctChoiceId: "a",
    explanation:
      "Primarni přidělení dava amatérské službě přednost, ale neznamena vylucnost. Pasmo je stale sdileno, ale amater ma ochranu. Viz slovnik: přidělení spektra.",
    relatedLessonIds: ["frequencies-01"],
    tags: ["predpisy", "recall"],
  },
  {
    id: "O-FRQ-009",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Vzorec pro vypocet vlnové délky z frekvence zni:",
    choices: [
      { id: "a", text: "lambda = 300 / f [MHz]" },
      { id: "b", text: "lambda = f [MHz] / 300" },
      { id: "c", text: "lambda = f [MHz] x 300" },
      { id: "d", text: "lambda = 300 + f [MHz]" },
    ],
    correctChoiceId: "a",
    explanation:
      "lambda [m] = 300 / f [MHz]. Delenim, ne nasobenim ci scitanim. Vzorec vychází z c = f x lambda, kde c = 3 x 10^8 m/s. Viz vzorce.",
    relatedLessonIds: ["frequencies-01"],
    tags: ["vlnova-delka", "recall"],
  },
  {
    id: "O-FRQ-010",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Ktere z následujících pásem je HF pásmo?",
    choices: [
      { id: "a", text: "14 MHz (20 m)" },
      { id: "b", text: "144 MHz (2 m)" },
      { id: "c", text: "430 MHz (70 cm)" },
      { id: "d", text: "1296 MHz (23 cm)" },
    ],
    correctChoiceId: "a",
    explanation:
      "HF = 3-30 MHz. 14 MHz patri do tohoto rozsahu. 144 MHz je VHF, 430 MHz je UHF, 1296 MHz jsou mikrovlny. Viz slovnik: HF.",
    relatedLessonIds: ["frequencies-01"],
    tags: ["pasma", "recall"],
  },

  // -----------------------------------------------------------------------
  // Modes and bandplan (frequencies-02)
  // -----------------------------------------------------------------------
  {
    id: "O-FRQ-011",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Jaka je typicka šířka pásma signálu CW (telegrafie)?",
    choices: [
      { id: "a", text: "Priblizne 500 Hz" },
      { id: "b", text: "Priblizne 2,4 kHz" },
      { id: "c", text: "Priblizne 16 kHz" },
      { id: "d", text: "Priblizne 6 kHz" },
    ],
    correctChoiceId: "a",
    explanation:
      "CW signál zabira přibližně 500 Hz. 2,4 kHz je SSB, 16 kHz je FM, 6 kHz je AM. CW je nejuzsi běžné používaný mod. Viz slovnik: CW.",
    relatedLessonIds: ["frequencies-02"],
    tags: ["druhy-provozu", "recall"],
  },
  {
    id: "O-FRQ-012",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Jaka je typicka šířka pásma SSB signálu?",
    choices: [
      { id: "a", text: "Priblizne 2,4 kHz" },
      { id: "b", text: "Priblizne 500 Hz" },
      { id: "c", text: "Priblizne 16 kHz" },
      { id: "d", text: "Priblizne 50 kHz" },
    ],
    correctChoiceId: "a",
    explanation:
      "SSB signál zabira přibližně 2,4 kHz (jedno postranli pásmo). 500 Hz je CW, 16 kHz je FM. Viz slovnik: SSB.",
    relatedLessonIds: ["frequencies-02"],
    tags: ["druhy-provozu", "recall"],
  },
  {
    id: "O-FRQ-013",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Proc se CW segment v bandplanu nachazi na spodnim okraji pásma?",
    choices: [
      { id: "a", text: "CW ma nejuzsi sirku pasma, coz umoznuje nejhustejsi provoz" },
      { id: "b", text: "CW signaly se lepe siri na nizsich frekvencich" },
      { id: "c", text: "Je to nahodne historicke rozhodnuti" },
      { id: "d", text: "CW vyzaduje mensi vykon, proto je dole" },
    ],
    correctChoiceId: "a",
    explanation:
      "Bandplan IARU radi módy od nejuzsiho po nejsirsi. CW (500 Hz) umožňuje nejvetsi počet stanic v danem useku. Sireni nesouvisri s pozici v pásmu. Viz bandplan.",
    relatedLessonIds: ["frequencies-02"],
    tags: ["bandplan", "analyze"],
  },
  {
    id: "O-FRQ-014",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Ktery druh provozu zabira nejsirsi pásmo?",
    choices: [
      { id: "a", text: "FM" },
      { id: "b", text: "CW" },
      { id: "c", text: "SSB" },
      { id: "d", text: "PSK31" },
    ],
    correctChoiceId: "a",
    explanation:
      "FM zabira přibližně 16 kHz, SSB 2,4 kHz, CW 500 Hz, PSK31 přibližně 31 Hz. FM je ze všech uvedenych nejsirsi. Viz porovnani módu.",
    relatedLessonIds: ["frequencies-02"],
    tags: ["druhy-provozu", "analyze"],
  },
  {
    id: "O-FRQ-015",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "V segmentu 144,000-144,150 MHz je povolen provoz:",
    choices: [
      { id: "a", text: "CW a SSB" },
      { id: "b", text: "Pouze FM" },
      { id: "c", text: "Pouze digitalni mody" },
      { id: "d", text: "Vsechny druhy provozu" },
    ],
    correctChoiceId: "a",
    explanation:
      "Spodni část pásma 2 m (144,000-144,150 MHz) je podle bandplanu IARU určena pro CW a SSB. FM provoz začíná od 145,200 MHz. Viz bandplan IARU Region 1.",
    relatedLessonIds: ["frequencies-02"],
    tags: ["bandplan", "recall"],
  },
  {
    id: "O-FRQ-016",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Jaka je typicka šířka pásma AM signálu?",
    choices: [
      { id: "a", text: "Priblizne 6 kHz" },
      { id: "b", text: "Priblizne 2,4 kHz" },
      { id: "c", text: "Priblizne 500 Hz" },
      { id: "d", text: "Priblizne 25 kHz" },
    ],
    correctChoiceId: "a",
    explanation:
      "AM signál ma dvě postrani pásma po 3 kHz, celkem přibližně 6 kHz. SSB prenasi jen jedno postranri pásmo (2,4 kHz), proto je uspornejsi. Viz slovnik: AM.",
    relatedLessonIds: ["frequencies-02"],
    tags: ["druhy-provozu", "recall"],
  },
  {
    id: "O-FRQ-017",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Proc se FM na kratkych vlnach (HF) používá jen vyjimecne?",
    choices: [
      { id: "a", text: "FM zabira prilis siroky kmitoctovy prostor, ktery je na HF omezeny" },
      { id: "b", text: "FM nefunguje na frekvencich pod 30 MHz" },
      { id: "c", text: "FM vyzaduje prilis vysoky vykon na HF" },
      { id: "d", text: "FM neni na HF povolena zadnym predpisem" },
    ],
    correctChoiceId: "a",
    explanation:
      "FM zabira 16 kHz, SSB jen 2,4 kHz. Na HF je spektrum omezene a FM by zabrala misto pro vice SSB stanic. FM na HF funguje (např. 29,6 MHz), ale není efektivni. Viz bandplan.",
    relatedLessonIds: ["frequencies-02"],
    tags: ["druhy-provozu", "analyze"],
  },
  {
    id: "O-FRQ-018",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Co je IARU bandplan?",
    choices: [
      { id: "a", text: "Doporuceny plan rozdeleni amterskych pasem podle druhu provozu" },
      { id: "b", text: "Zakon stanoveny Mezinarodni telekomunikacni unii" },
      { id: "c", text: "Seznam povolenych volacich znacek" },
      { id: "d", text: "Technicky standard pro vyrobu vysilacu" },
    ],
    correctChoiceId: "a",
    explanation:
      "Bandplan IARU je doporučení, jak používat amatérská pásma. Neni to zákon, ale radioamateri jej maji dodržovat. IARU je mezinárodní amatérská unie. Viz slovnik: IARU.",
    relatedLessonIds: ["frequencies-02"],
    tags: ["bandplan", "recall"],
  },
  {
    id: "O-FRQ-019",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Ktery mod se běžné používá pro fonicky provoz na VHF/UHF repeaterech?",
    choices: [
      { id: "a", text: "FM" },
      { id: "b", text: "SSB" },
      { id: "c", text: "AM" },
      { id: "d", text: "CW" },
    ],
    correctChoiceId: "a",
    explanation:
      "Na VHF/UHF prevladacich se používá FM diky dobre kvalite zvuku a jednoduchosti. SSB se používá pro DX (daleka spojení) na spodni části 2 m pásma. Viz slovnik: FM.",
    relatedLessonIds: ["frequencies-02"],
    tags: ["druhy-provozu", "recall"],
  },
  {
    id: "O-FRQ-020",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Digitalni módy (FT8, PSK31) se v bandplanu IARU typicky nachazeji:",
    choices: [
      { id: "a", text: "Mezi segmentem CW a SSB" },
      { id: "b", text: "Na uplnem konci pasma" },
      { id: "c", text: "Na stejnych frekvencich jako FM" },
      { id: "d", text: "Nemaji vyhrazeny segment" },
    ],
    correctChoiceId: "a",
    explanation:
      "Digitalni módy maji uzkou šířku pásma (mezi CW a SSB), proto je bandplan radi mezi tyto segmenty. Napr. na 20 m: 14,070-14,099 MHz. Viz bandplan IARU.",
    relatedLessonIds: ["frequencies-02"],
    tags: ["bandplan", "digitalni", "recall"],
  },

  // -----------------------------------------------------------------------
  // Emergency frequencies (frequencies-03)
  // -----------------------------------------------------------------------
  {
    id: "O-FRQ-021",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Jaka je amatérská nouzova frekvence na VHF?",
    choices: [
      { id: "a", text: "145,500 MHz" },
      { id: "b", text: "144,300 MHz" },
      { id: "c", text: "146,000 MHz" },
      { id: "d", text: "145,000 MHz" },
    ],
    correctChoiceId: "a",
    explanation:
      "145,500 MHz je mezinárodně uznana amatérská nouzova (volaci) frekvence na VHF. Ostatni frekvence nemaji tento speciální status. Viz nouzové frekvence.",
    relatedLessonIds: ["frequencies-03"],
    tags: ["nouzove-frekvence", "recall"],
  },
  {
    id: "O-FRQ-022",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Nouzova volaci frekvence na KV (HF) je:",
    choices: [
      { id: "a", text: "14,300 MHz" },
      { id: "b", text: "14,100 MHz" },
      { id: "c", text: "7,110 MHz" },
      { id: "d", text: "3,500 MHz" },
    ],
    correctChoiceId: "a",
    explanation:
      "14,300 MHz je hlavní mezinárodní amatérská nouzova frekvence na KV. 14,100 MHz je frekvence majaku, ne nouzova. Viz nouzové frekvence.",
    relatedLessonIds: ["frequencies-03"],
    tags: ["nouzove-frekvence", "recall"],
  },
  {
    id: "O-FRQ-023",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Jaka je amatérská nouzova frekvence na UHF?",
    choices: [
      { id: "a", text: "433,500 MHz" },
      { id: "b", text: "430,000 MHz" },
      { id: "c", text: "438,000 MHz" },
      { id: "d", text: "435,000 MHz" },
    ],
    correctChoiceId: "a",
    explanation:
      "433,500 MHz je amatérská nouzova frekvence na UHF. Ostatni uvedene frekvence nemaji status nouzových. Viz nouzové frekvence.",
    relatedLessonIds: ["frequencies-03"],
    tags: ["nouzove-frekvence", "recall"],
  },
  {
    id: "O-FRQ-024",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Co musí radioamater udělat, kdyz zaslechne signál MAYDAY?",
    choices: [
      { id: "a", text: "Okamzite prestat vysilat a naslouchat" },
      { id: "b", text: "Prepnout na jinou frekvenci" },
      { id: "c", text: "Zvysit vykon a pokusit se navazat spojeni" },
      { id: "d", text: "Vypnout stanici a zavolat policii" },
    ],
    correctChoiceId: "a",
    explanation:
      "Povinnosti je okamžitě přestat vysílat a naslouchat. Prepnuti na jinou frekvenci by znemoznilo sledovani situace. Viz nouzový provoz.",
    relatedLessonIds: ["frequencies-03"],
    tags: ["nouzovy-provoz", "recall"],
  },
  {
    id: "O-FRQ-025",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Signal MAYDAY označuje:",
    choices: [
      { id: "a", text: "Tisen - bezprostredni ohrozeni zivota" },
      { id: "b", text: "Nalehavy stav bez ohrozeni zivota" },
      { id: "c", text: "Bezpecnostni varovani" },
      { id: "d", text: "Zkousku nouzoveho vysilani" },
    ],
    correctChoiceId: "a",
    explanation:
      "MAYDAY je nejvyšší stupen priority - bezprostredni ohrozeni zivota. PAN PAN je naléhavost bez primeho ohrozeni, SECURITE je bezpečnostní zpráva. Viz slovnik: MAYDAY.",
    relatedLessonIds: ["frequencies-03"],
    tags: ["nouzovy-provoz", "recall"],
  },
  {
    id: "O-FRQ-026",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Signal PAN PAN označuje:",
    choices: [
      { id: "a", text: "Nalehavou situaci bez bezprostredniho ohrozeni zivota" },
      { id: "b", text: "Bezprostredni ohrozeni zivota" },
      { id: "c", text: "Bezpecnostni varovani pro vsechny stanice" },
      { id: "d", text: "Konec nouzoveho provozu" },
    ],
    correctChoiceId: "a",
    explanation:
      "PAN PAN signalizuje vaznou situaci, která není bezprostredne zivotu nebezpecna. MAYDAY je ohrozeni zivota, SECURITE je varovani. Viz slovnik: PAN PAN.",
    relatedLessonIds: ["frequencies-03"],
    tags: ["nouzovy-provoz", "recall"],
  },
  {
    id: "O-FRQ-027",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Signal SECURITE označuje:",
    choices: [
      { id: "a", text: "Bezpecnostni zpravu - varovani pred nebezpecim" },
      { id: "b", text: "Bezprostredni ohrozeni zivota" },
      { id: "c", text: "Nalehavou situaci vyzadujici pomoc" },
      { id: "d", text: "Zabezpecenou (sifrovanou) komunikaci" },
    ],
    correctChoiceId: "a",
    explanation:
      "SECURITE je informativni bezpečnostní varovani (např. nebezpecne pocasi). Nesouvisí se sifrovanim. Viz slovnik: SECURITE.",
    relatedLessonIds: ["frequencies-03"],
    tags: ["nouzovy-provoz", "recall"],
  },
  {
    id: "O-FRQ-028",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Nouzove amatérské frekvence se smeji používat:",
    choices: [
      { id: "a", text: "Pouze pro nouzovou komunikaci a cviceni" },
      { id: "b", text: "Pro jakykoli amatersky provoz" },
      { id: "c", text: "Jen s povolenim CTU" },
      { id: "d", text: "Pouze profesionalni zachranarskou sluzbou" },
    ],
    correctChoiceId: "a",
    explanation:
      "Nouzove frekvence jsou určený pro skutecny nouzový provoz a organizovana cviceni. Bezny provoz na nich není zadouci. Viz nouzový provoz.",
    relatedLessonIds: ["frequencies-03"],
    tags: ["nouzove-frekvence", "recall"],
  },
  {
    id: "O-FRQ-029",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Ktera uroven nouzového signálu ma nejvyšší prioritu?",
    choices: [
      { id: "a", text: "MAYDAY" },
      { id: "b", text: "PAN PAN" },
      { id: "c", text: "SECURITE" },
      { id: "d", text: "Vsechny maji stejnou prioritu" },
    ],
    correctChoiceId: "a",
    explanation:
      "Poradi priority: MAYDAY (nejvyšší) > PAN PAN > SECURITE > běžný provoz. MAYDAY znamená bezprostredni ohrozeni zivota. Viz nouzové signály.",
    relatedLessonIds: ["frequencies-03"],
    tags: ["nouzovy-provoz", "recall"],
  },
  {
    id: "O-FRQ-030",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Nouzova komunikace ma přednost:",
    choices: [
      { id: "a", text: "Pred veskerym beznym provozem na jakemkoli kmitoctu" },
      { id: "b", text: "Pouze na vyhrazenych nouzovych frekvencich" },
      { id: "c", text: "Pouze pokud je schvalena CTU" },
      { id: "d", text: "Jen v ramci jednoho amatskeho pasma" },
    ],
    correctChoiceId: "a",
    explanation:
      "Nouzova komunikace ma absolutni přednost na jakemkoli kmitočtů, nejen na nouzových frekvencích. Neni třeba schvaleni CTU. Viz nouzový provoz.",
    relatedLessonIds: ["frequencies-03"],
    tags: ["nouzovy-provoz", "analyze"],
  },

  // -----------------------------------------------------------------------
  // Power limits (frequencies-04)
  // -----------------------------------------------------------------------
  {
    id: "O-FRQ-031",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Jaky je maximální povoleny výkon pro držitele povolení třídy A (HAREC)?",
    choices: [
      { id: "a", text: "750 W PEP" },
      { id: "b", text: "100 W PEP" },
      { id: "c", text: "1000 W PEP" },
      { id: "d", text: "500 W ERP" },
    ],
    correctChoiceId: "a",
    explanation:
      "Cesky provozní řád stanovi pro třídu A maximum 750 W PEP. 100 W je limit třídy N, 1000 W platí v nekterych jinych zemích. Viz předpisy.",
    relatedLessonIds: ["frequencies-04"],
    tags: ["vykon", "recall"],
  },
  {
    id: "O-FRQ-032",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Jaky je maximální povoleny výkon pro třídu N (novice)?",
    choices: [
      { id: "a", text: "100 W PEP" },
      { id: "b", text: "750 W PEP" },
      { id: "c", text: "10 W PEP" },
      { id: "d", text: "250 W PEP" },
    ],
    correctChoiceId: "a",
    explanation:
      "Trida N (novice) ma limit 100 W PEP. 750 W je třída A (HAREC). 10 W je příliš nizko, 250 W není zadnou třídou stanoveny limit. Viz předpisy.",
    relatedLessonIds: ["frequencies-04"],
    tags: ["vykon", "recall"],
  },
  {
    id: "O-FRQ-033",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Co znamená zkratka PEP?",
    choices: [
      { id: "a", text: "Peak Envelope Power - spickovy vykon obalky" },
      { id: "b", text: "Power Effective Peak - efektivni spickovy vykon" },
      { id: "c", text: "Primary Emission Power - primarni vykon emise" },
      { id: "d", text: "Pulse Energy Power - pulsni energeticky vykon" },
    ],
    correctChoiceId: "a",
    explanation:
      "PEP = Peak Envelope Power = stredni výkon v jedné RF periode pri spicce modulacni obalky. Je to standardní způsob mereni výkonu vysílače. Viz slovnik: PEP.",
    relatedLessonIds: ["frequencies-04"],
    tags: ["vykon", "recall"],
  },
  {
    id: "O-FRQ-034",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Co je ERP (Effective Radiated Power)?",
    choices: [
      { id: "a", text: "Efektivni vyzareny vykon zahrnujici zisk anteny a ztraty ve vedeni" },
      { id: "b", text: "Vykon mereny na vystupu vysilace" },
      { id: "c", text: "Maximalni povoleny vykon stanoveny predpisy" },
      { id: "d", text: "Prumerny vykon za jednu minutu vysilani" },
    ],
    correctChoiceId: "a",
    explanation:
      "ERP = výkon vysílače x zisk antény / ztráty v kabelu. Zahrnuje celou vysílací cestu včetně antény. Vykon na vystupu vysílače je jen PEP. Viz slovnik: ERP.",
    relatedLessonIds: ["frequencies-04"],
    tags: ["vykon", "recall"],
  },
  {
    id: "O-FRQ-035",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Radioamater ma vysílat:",
    choices: [
      { id: "a", text: "Nejmensim vykonem potrebnym pro spolehive spojeni" },
      { id: "b", text: "Vzdy na maximalnim povolenem vykonu" },
      { id: "c", text: "Presne na polovine maximalniho vykonu" },
      { id: "d", text: "Libovolnym vykonem bez omezeni" },
    ],
    correctChoiceId: "a",
    explanation:
      "Predpisy vyzaduji používat minimální výkon nutný k navazani spojení. Zbytecne vysoký výkon způsobuje rušení ostatnim stanicím. Viz provozní pravidla.",
    relatedLessonIds: ["frequencies-04"],
    tags: ["vykon", "recall"],
  },
  {
    id: "O-FRQ-036",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Platri na všech amatérských pásmech stejny výkonový limit?",
    choices: [
      { id: "a", text: "Ne, na nekterych pasmech mohou platit snizene limity" },
      { id: "b", text: "Ano, vzdy 750 W PEP pro tridu A" },
      { id: "c", text: "Ano, ale jen pro fonickyy provoz" },
      { id: "d", text: "Ne, na VHF/UHF je limit vzdy vyssi" },
    ],
    correctChoiceId: "a",
    explanation:
      "Na nekterych pásmech ci v urcitych oblastech mohou platit prisnejsi omezení. Obecny limit 750 W nemusí platit vsude stejne. Viz provozní řád.",
    relatedLessonIds: ["frequencies-04"],
    tags: ["vykon", "analyze"],
  },
  {
    id: "O-FRQ-037",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Jak se liší PEP od ERP?",
    choices: [
      { id: "a", text: "PEP je vykon na vystupu vysilace, ERP zahrnuje i zisk anteny" },
      { id: "b", text: "PEP a ERP jsou totez" },
      { id: "c", text: "ERP je vzdy nizsi nez PEP" },
      { id: "d", text: "PEP zahrnuje zisk anteny, ERP ne" },
    ],
    correctChoiceId: "a",
    explanation:
      "PEP se meri na vystupu vysílače. ERP zahrnuje celou vysílací cestu: výkon vysílače, ztráty v kabelu a zisk antény. S vysokim ziskem antény může byt ERP vyšší nez PEP. Viz slovnik: ERP, PEP.",
    relatedLessonIds: ["frequencies-04"],
    tags: ["vykon", "analyze"],
  },
  {
    id: "O-FRQ-038",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Proc je dulezite používat minimální potrebny výkon?",
    choices: [
      { id: "a", text: "Snizuje se ruseni ostatnich stanic a setri se energie" },
      { id: "b", text: "Vyssi vykon poskozuje antenuu" },
      { id: "c", text: "Nizsi vykon zlepsuje kvalitu signalu" },
      { id: "d", text: "Je to pouze doporuceni, neni to povinnost" },
    ],
    correctChoiceId: "a",
    explanation:
      "Minimalni výkon snižuje rušení na sdilenych frekvencích. Je to povinnost dana předpisy, ne pouhe doporučení. Vyssi výkon sam o sobe neposkozuje anténu. Viz provozní pravidla.",
    relatedLessonIds: ["frequencies-04"],
    tags: ["vykon", "analyze"],
  },
  {
    id: "O-FRQ-039",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Radioamater třídy N chce vysílat na pásmu 2 m. Jaky maximální výkon může pouzit?",
    choices: [
      { id: "a", text: "100 W PEP" },
      { id: "b", text: "750 W PEP" },
      { id: "c", text: "50 W PEP" },
      { id: "d", text: "10 W PEP" },
    ],
    correctChoiceId: "a",
    explanation:
      "Trida N ma na všech povolenychy pásmech limit 100 W PEP. 750 W je limit třídy A. Viz provozní řád.",
    relatedLessonIds: ["frequencies-04"],
    tags: ["vykon", "apply"],
  },
  {
    id: "O-FRQ-040",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Vysilac ma výkon 100 W a anterna ma zisk 10 dBi. Jak se zmeni ERP oproti PEP?",
    choices: [
      { id: "a", text: "ERP bude vyssi nez PEP diky zisku anteny" },
      { id: "b", text: "ERP bude nizsi nez PEP" },
      { id: "c", text: "ERP a PEP budou stejne" },
      { id: "d", text: "ERP nezavisi na antene" },
    ],
    correctChoiceId: "a",
    explanation:
      "Zisk antény 10 dBi znamená 10x vyšší ERP nez výkon na svorkach antény. ERP tedy bude vyšší nez PEP (za predpokladu malých ztrát v kabelu). Viz slovnik: ERP.",
    relatedLessonIds: ["frequencies-04"],
    tags: ["vykon", "analyze"],
  },
  {
    id: "O-FRQ-041",
    examPartId: "operating",
    sectionId: "frequencies",
    wording: "Co je Peak Envelope Power (PEP) přesně?",
    choices: [
      { id: "a", text: "Stredni vykon v jedne RF periode pri spicce modulacni obalky" },
      { id: "b", text: "Maximalni okamzity vykon v prubehu vysilani" },
      { id: "c", text: "Prumerny vykon za celou dobu vysilani" },
      { id: "d", text: "Vykon na antene vcetne ztrat v kabelu" },
    ],
    correctChoiceId: "a",
    explanation:
      "PEP je stredni výkon v jedné RF periode pri maximu modulacni obalky. Neni to okamžitý spickovy výkon ani prumernry výkon. Viz slovnik: PEP.",
    relatedLessonIds: ["frequencies-04"],
    tags: ["vykon", "recall"],
  },
];
